<a href="https://colab.research.google.com/github/angelaguzmanar/Salud/blob/main/Preprocesamiento_Salud.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd ### para manejo de datos
import sys
import numpy as np
import sqlite3 as sql

In [2]:
  #conectamos con Google Drive
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [3]:
#conectarse a BD  ANGELA
conn= sql.connect('/content/drive/MyDrive/Analitica3/Entrega_Marketing/db_salud')
cur=conn.cursor()

#ver las tablas que hay en la base de datos
cur.execute("select name from sqlite_master where type='table' ")
cur.fetchall()

[('egresos',), ('usuarios',), ('cronicos',)]

In [4]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


## Egresos

In [6]:
#dfegresos = pd.read_csv('/content/drive/MyDrive/caso salud analitica /RETO_df_egresos.csv')#, sep = ';' ,encoding='unicode_escape', on_bad_lines='skip')
#print(dfegresos.shape)
#dfegresos.info()

In [7]:
dfegresos = pd.read_excel('/content/drive/MyDrive/Analitica3/EntregaSalud/Entregable/RETO_df_egresos1.xlsx')#, sep = ';' ,encoding='unicode_escape', on_bad_lines='skip')
print(dfegresos.shape)
dfegresos.info()

(6376, 66)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6376 entries, 0 to 6375
Data columns (total 66 columns):
 #   Column                             Non-Null Count  Dtype  
---  ------                             --------------  -----  
 0   YEAR                               6376 non-null   int64  
 1   MES                                6376 non-null   object 
 2   NRO ATENCION                       6376 non-null   int64  
 3   NRO INGRESO                        6376 non-null   int64  
 4   SERVICIO HABILITADO COD            6376 non-null   float64
 5   SERVICIO HABILITADO                6376 non-null   object 
 6   TIPO IDENTIFICACION                6376 non-null   object 
 7   NRODOC                             6376 non-null   int64  
 8   FECHA NACIMIENTO                   6376 non-null   object 
 9   REGIMEN AFILIACION                 6376 non-null   object 
 10  EPS VALIDADA                       4103 non-null   object 
 11  MODALIDAD CONTRATO                 6376 non-n

In [8]:
# Calcula la suma de valores nulos por columna
nulos_por_columna = dfegresos.isnull().sum()

# Filtra las columnas con valores nulos (suma mayor que cero)
columnas_con_nulos = nulos_por_columna[nulos_por_columna > 0]

# Muestra las columnas con valores nulos
print(columnas_con_nulos)

EPS VALIDADA                         2273
FECHA INGRESO CLINICA                2271
FECHA INGRESO SERVICIO               2272
FECHA POSIBLE ALTA                   6223
FECHA RECAUDO                        4777
FECHA CAMILLERO                      4540
FECHA ENFERMERIA                     4923
FECHA FACTURACION AUDIFARMA          4296
FECHA FARMACIA                       4315
FECHA ASEO                           4395
DEMORA APLICACION MEDICAMENTO          15
DX RELACIONADO1 COD                    19
DX RELACIONADO2 COD                    67
DX RELACIONADO3 COD                   181
PERTINENCIA DIAGNOSTICA              5192
DX PRINCIPAL EGRESO CATEGORIA COD      72
DX PRINCIPAL EGRESO CAPITULO COD       72
CAUSA BASICA MUERTE COD              5810
CAUSA BASICA CATEGORIA COD           5812
CAUSA BASICA CAPITULO COD            5812
dtype: int64


In [9]:
dfegresos = dfegresos.dropna(subset=['FECHA INGRESO CLINICA'])

In [10]:
dfegresos['FECHA INGRESO SERVICIO'].fillna(dfegresos['FECHA INGRESO CLINICA'], inplace=True)

<ipython-input-10-cae057834405>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfegresos['FECHA INGRESO SERVICIO'].fillna(dfegresos['FECHA INGRESO CLINICA'], inplace=True)


In [11]:
moda = dfegresos['EPS VALIDADA'].mode()[0]

# Luego, usa fillna para reemplazar los NaN con la moda
dfegresos['EPS VALIDADA'] = dfegresos['EPS VALIDADA'].fillna(moda)

<ipython-input-11-2ab44e4c1628>:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfegresos['EPS VALIDADA'] = dfegresos['EPS VALIDADA'].fillna(moda)


In [12]:
dfegresos['DEMORA APLICACION MEDICAMENTO'] = dfegresos['DEMORA APLICACION MEDICAMENTO'].str.split(':').str[0]


<ipython-input-12-c524ce338516>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfegresos['DEMORA APLICACION MEDICAMENTO'] = dfegresos['DEMORA APLICACION MEDICAMENTO'].str.split(':').str[0]


In [13]:
dfegresos['DEMORA APLICACION MEDICAMENTO'].fillna(0, inplace = True)

<ipython-input-13-363d865394fd>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfegresos['DEMORA APLICACION MEDICAMENTO'].fillna(0, inplace = True)


In [14]:
dfegresos['DEMORA APLICACION MEDICAMENTO'].unique()

array([0, '-89', '-163', '-105', '-331', '-2', '-170', '-278', '-189',
       '-65', '-248', '-22', '-864', '-172', '-57', '-250', '-53', '-181',
       '-5', '-54', '-80', '-366', '-64', '-464', '-30', '-38', '-199',
       '0', '-86', '-18', '-58', '-31', '-28', '-61', '-7', '-35', '-19',
       '-37', '-207', '-491', '-227', '-942', '-84', '-515', '-216',
       '-150', '-48', '-33', '-129', '-34', '-24', '-396', '-21', '-66',
       '-149', '-291', '-442', '-317', '-16', '-12', '-44', '-365', '-63',
       '-223', '-157', '-241', '-60', '-135', '-286', '-179', '-46',
       '-224', '-20', '-161', '-192', '-154', '-188', '-121', '-13',
       '-51', '-8', '-15', '-85', '-437', '-208', '-114', '-196', '-200',
       '-125', '-148', '-173', '-56', '-49', '-108', '-133', '-106',
       '-109', '-277', '-585', '-9', '-94', '-99', '-164', '-298', '-17',
       '-25', '-155', '-110', '-302', '-131', '-101', '-584', '-198',
       '-230', '-343', '-42', '-225', '-103', '-120', '-11', '-178

In [15]:
moda = dfegresos['DX PRINCIPAL EGRESO CAPITULO COD'].mode()[0]

# Luego, usa fillna para reemplazar los NaN con la moda
dfegresos['DX PRINCIPAL EGRESO CAPITULO COD'] = dfegresos['DX PRINCIPAL EGRESO CAPITULO COD'].fillna(moda)

In [16]:
dfegresos = dfegresos.drop(columns=['DX PRINCIPAL EGRESO CATEGORIA COD','PERTINENCIA DIAGNOSTICA','DX RELACIONADO1 COD','DX RELACIONADO2 COD','DX RELACIONADO3 COD','DEMORA ASIGNACION CAMA','CAUSA BASICA MUERTE COD', 'CAUSA BASICA CATEGORIA COD', 'CAUSA BASICA CAPITULO COD','FECHA POSIBLE ALTA', 'FECHA RECAUDO', 'FECHA CAMILLERO', 'FECHA ENFERMERIA', 'FECHA FACTURACION AUDIFARMA', 'FECHA FARMACIA', 'FECHA ASEO'])

In [17]:
dfegresos = dfegresos.apply(lambda x: x.str.lower() if x.dtype == 'object' else x)

In [18]:
dfegresos['NRO CAMA'].fillna('sin informacion', inplace = True)
dfegresos['NRO CAMA ANTERIOR'].fillna('sin informacion', inplace = True)

In [19]:
dfegresos.columns

Index(['YEAR', 'MES', 'NRO ATENCION', 'NRO INGRESO', 'SERVICIO HABILITADO COD',
       'SERVICIO HABILITADO', 'TIPO IDENTIFICACION', 'NRODOC',
       'FECHA NACIMIENTO', 'REGIMEN AFILIACION', 'EPS VALIDADA',
       'MODALIDAD CONTRATO', 'FUENTE FINANCIACION1', 'FUENTE FINANCIACION2',
       'SERVICIO ADMITE', 'BLOQUE ANTERIOR', 'PISO ANTERIOR',
       'SERVICIO ANTERIOR', 'NRO CAMA ANTERIOR', 'VIA INGRESO', 'BLOQUE',
       'UNIDAD ESTRATEGICA', 'PISO', 'NRO CAMA', 'SERVICIO EGRESO',
       'TIPO EGRESO', 'FECHA INGRESO CLINICA', 'FECHA INGRESO SERVICIO',
       'FECHA ALTA MEDICA', 'FECHA SALIDA', 'DEMORA APLICACION MEDICAMENTO',
       'DEMORA SALIDA CLINICA (DIAS)', 'TRANSFUSION SANGRE', 'ANTIBIOTICO',
       'ALTA MEDICA', 'POSIBLE ALTA', 'DXPRINCIPAL EGRESO COD',
       'DXPRINCIPAL EGRESO', 'DX RELACIONADO1', 'DX RELACIONADO2',
       'DX RELACIONADO3', 'TIPO DIAGNOSTICO PRINCIPAL',
       'DX PRINCIPAL EGRESO CATEGORIA', 'DX PRINCIPAL EGRESO CAPITULO COD',
       'DX PRINCIPAL E

In [20]:
for columna in dfegresos.columns[:]:
  print('\n {}'.format(columna))
  print(dfegresos[columna].unique()) #Tipo identificacion cc se puede eliminar solo hay 1 valor que es cc


 YEAR
[2018 2021 2017]

 MES
['febrero' 'mayo' 'julio' 'octubre' 'noviembre' 'marzo' 'junio' 'agosto'
 'septiembre' 'diciembre' 'abril' 'enero']

 NRO ATENCION
[3912821 4023613 4080166 ... 3961138 5883105 5857866]

 NRO INGRESO
[2159592 2254075 2292863 ... 2204868 4110965 4084538]

 SERVICIO HABILITADO COD
[501. 101. 110. 107.  -1.]

 SERVICIO HABILITADO
['urgencias >= 24 horas' 'general adultos' 'urgencias < 24 horas'
 'cuidado intensivo adultos' 'cuidado intermedio adultos'
 'sin informacion']

 TIPO IDENTIFICACION
['cc']

 NRODOC
[308185 310222 307108 ... 308759 313987 313921]

 FECHA NACIMIENTO
['1937-07-18 00:00:00.000' '1930-03-24 00:00:00.000'
 '1933-02-23 00:00:00.000' ... '1951-06-08 00:00:00.000'
 '1953-09-30 00:00:00.000' '1960-06-09 00:00:00.000']

 REGIMEN AFILIACION
['contributivo' 'soat' 'sin informaciã³n' 'subsidiado' 'particular'
 'medicina prepagada']

 EPS VALIDADA
['nueva eps s.a. pgp' 'nueva eps s.a.' 'no afiliado particular'
 'axa seguros colpatria s.a' 'allianz 

In [21]:
# Convierte la columna 'Fecha_Hora' al formato de fecha y hora
dfegresos['FECHA INGRESO CLINICA'] = pd.to_datetime(dfegresos['FECHA INGRESO CLINICA'])

# Extrae solo la parte de la fecha
dfegresos['FECHA INGRESO CLINICA'] = dfegresos['FECHA INGRESO CLINICA'].dt.date

In [22]:
# Convierte la columna 'Fecha_Hora' al formato de fecha y hora
dfegresos['FECHA SALIDA'] = pd.to_datetime(dfegresos['FECHA SALIDA'])

# Extrae solo la parte de la fecha
dfegresos['FECHA SALIDA'] = dfegresos['FECHA SALIDA'].dt.date

In [23]:
# Resta las fechas de salida y entrada para obtener la duración en días
dfegresos['Dias_Estancia'] = (dfegresos['FECHA SALIDA'] - dfegresos['FECHA INGRESO CLINICA']).dt.days

In [24]:
def clasificar_fila(texto):
    opciones = {
        'urgencias': 'urgencias',
        'sala de rehidratación oral': 'sala de rehidratación oral',
        'reanimación covid': 'reanimación covid',
        'cirugia': 'cirugia',
        'era': 'era',
        'fast track': 'fast track',
        'medicina interna': 'medicina interna',
        'uce': 'uce',
        'toma de muestras': 'toma de muestras',
        'sai': 'sai',
        'remitidos': 'remitidos',
        'expansión': 'expansión',
        'uci': 'uci',
        'nueva eps': 'nueva eps',
        'sala de altas': 'sala de altas',
        'oriente': 'oriente',
        'sala vip udea': 'sala vip udea',
        'occidente': 'occidente',
        'observación individual': 'observación individual',
        'sala de transición': 'sala de transición',
        'procedimientos oncologicos': 'procedimientos oncologicos',
        'expansiã³n': 'expansiã³n',
        'observaciã³n': 'observaciã³n',
         'sala de transiciã³n':'sala de transiciã³n',
       'sala de rehidrataciã³n oral':'sala de rehidrataciã³n oral',
        'reanimaciã³n covid':'reanimaciã³n covid'
    }

    for opcion, etiqueta in opciones.items():
        if opcion in texto.lower():
            return etiqueta
    return 'No clasificado'

In [25]:
dfegresos['SERVICIO ANTERIOR_C'] = dfegresos['SERVICIO ANTERIOR'].apply(clasificar_fila)

In [26]:
dfegresos['SERVICIO EGRESO_C'] = dfegresos['SERVICIO EGRESO'].apply(clasificar_fila)

In [27]:
columnas_a_eliminar= ['SERVICIO ANTERIOR','FECHA NACIMIENTO','SERVICIO EGRESO','NRO CAMA ANTERIOR', 'TIPO IDENTIFICACION', 'NRO CAMA', 'POSIBLE ALTA',  'DXPRINCIPAL EGRESO COD','DXPRINCIPAL EGRESO', 'DX RELACIONADO1', 'DX RELACIONADO2',  'DX RELACIONADO3', 'DX PRINCIPAL EGRESO CATEGORIA', 'CAUSA BASICA MUERTE', 'CAUSA BASICA CATEGORIA']

In [28]:
dfegresos = dfegresos.drop(columnas_a_eliminar, axis=1)

In [29]:
for i in dfegresos.columns[:]:
  dfegresos[i].replace('sin informaciã³n', 'sin informacion', inplace=True)

In [30]:
columnas = ['FECHA INGRESO CLINICA', 'FECHA INGRESO SERVICIO', 'FECHA ALTA MEDICA',
       'FECHA SALIDA', 'DEMORA APLICACION MEDICAMENTO',
       'DEMORA SALIDA CLINICA (DIAS)']

In [31]:
dfegresos = dfegresos.drop(columnas, axis=1)

In [32]:
moda_servicio_habilitado = dfegresos['SERVICIO HABILITADO COD'].mode()[0]

# Reemplaza todos los valores -1.0 por la moda
dfegresos['SERVICIO HABILITADO COD'].replace(-1.0, moda_servicio_habilitado, inplace=True)

In [33]:
moda_servicio_habilitado = dfegresos['REGIMEN AFILIACION'].mode()[0]

# Reemplaza todos los valores -1.0 por la moda
dfegresos['REGIMEN AFILIACION'].replace('sin informacion', moda_servicio_habilitado, inplace=True)

In [34]:
moda_servicio_habilitado = dfegresos['FUENTE FINANCIACION1'].mode()[0]

# Reemplaza todos los valores -1.0 por la moda
dfegresos['FUENTE FINANCIACION1'].replace('sin informacion', moda_servicio_habilitado, inplace=True)

In [35]:
moda_servicio_habilitado = dfegresos['MODALIDAD CONTRATO'].mode()[0]

# Reemplaza todos los valores -1.0 por la moda
dfegresos['MODALIDAD CONTRATO'].replace('sin informacion', moda_servicio_habilitado, inplace=True)

In [36]:
moda_servicio_habilitado = dfegresos['FUENTE FINANCIACION2'].mode()[0]

# Reemplaza todos los valores -1.0 por la moda
dfegresos['FUENTE FINANCIACION2'].replace('sin informacion', moda_servicio_habilitado, inplace=True)

In [37]:
moda_servicio_habilitado = dfegresos['SERVICIO ADMITE'].mode()[0]

# Reemplaza todos los valores -1.0 por la moda
dfegresos['SERVICIO ADMITE'].replace('sin informacion en base de datos', moda_servicio_habilitado, inplace=True)

In [38]:
moda_servicio_habilitado = dfegresos['VIA INGRESO'].mode()[0]

# Reemplaza todos los valores -1.0 por la moda
dfegresos['VIA INGRESO'].replace('sin informacion en base de datos', moda_servicio_habilitado, inplace=True)

In [39]:
moda_servicio_habilitado = dfegresos['BLOQUE'].mode()[0]

# Reemplaza todos los valores -1.0 por la moda
dfegresos['BLOQUE'].replace('sin informacion', moda_servicio_habilitado, inplace=True)

In [40]:
moda_servicio_habilitado = dfegresos['PISO'].mode()[0]

# Reemplaza todos los valores -1.0 por la moda
dfegresos['PISO'].replace('sin informacion', moda_servicio_habilitado, inplace=True)

In [41]:
moda_servicio_habilitado = dfegresos['TIPO EGRESO'].mode()[0]

# Reemplaza todos los valores -1.0 por la moda
dfegresos['TIPO EGRESO'].replace('sin informacion', moda_servicio_habilitado, inplace=True)

In [42]:
dfegresos = dfegresos.drop('TIPO DIAGNOSTICO PRINCIPAL', axis=1) #mas 50% sin info

In [43]:
dfegresos = dfegresos.drop('CAUSA BASICA CAPITULO', axis=1) #mas 50% sin info

In [44]:
# Porcentaje de nulos que presenta nuetra base de datos
round(dfegresos.isnull().sum().sum()/dfegresos.size, 4)*100


0.0

In [45]:
dfegresos.columns

Index(['YEAR', 'MES', 'NRO ATENCION', 'NRO INGRESO', 'SERVICIO HABILITADO COD',
       'SERVICIO HABILITADO', 'NRODOC', 'REGIMEN AFILIACION', 'EPS VALIDADA',
       'MODALIDAD CONTRATO', 'FUENTE FINANCIACION1', 'FUENTE FINANCIACION2',
       'SERVICIO ADMITE', 'BLOQUE ANTERIOR', 'PISO ANTERIOR', 'VIA INGRESO',
       'BLOQUE', 'UNIDAD ESTRATEGICA', 'PISO', 'TIPO EGRESO',
       'TRANSFUSION SANGRE', 'ANTIBIOTICO', 'ALTA MEDICA',
       'DX PRINCIPAL EGRESO CAPITULO COD', 'DX PRINCIPAL EGRESO CAPITULO',
       'PROFESIONAL ESPECIALIDAD', 'PROFESIONAL ESPECIALIDAD GRD',
       'Dias_Estancia', 'SERVICIO ANTERIOR_C', 'SERVICIO EGRESO_C'],
      dtype='object')

In [46]:
#llevar tabla a sql
dfegresos.to_sql('egresos', conn, index=False, if_exists='replace')

4105

In [47]:
pd.set_option('display.max_columns', None)
pd.set_option('display.expand_frame_repr', False)
dfegresos

YEAR        MES  NRO ATENCION  NRO INGRESO  SERVICIO HABILITADO COD         SERVICIO HABILITADO  NRODOC REGIMEN AFILIACION        EPS VALIDADA MODALIDAD CONTRATO FUENTE FINANCIACION1 FUENTE FINANCIACION2              SERVICIO ADMITE  BLOQUE ANTERIOR    PISO ANTERIOR VIA INGRESO    BLOQUE       UNIDAD ESTRATEGICA       PISO                    TIPO EGRESO TRANSFUSION SANGRE ANTIBIOTICO      ALTA MEDICA DX PRINCIPAL EGRESO CAPITULO COD                       DX PRINCIPAL EGRESO CAPITULO PROFESIONAL ESPECIALIDAD                 PROFESIONAL ESPECIALIDAD GRD  Dias_Estancia SERVICIO ANTERIOR_C SERVICIO EGRESO_C
2     2018    febrero       3912821      2159592                    501.0       urgencias >= 24 horas  308185       contributivo  nueva eps s.a. pgp                pgp            nueva eps            nueva eps  urgencias generales sã³tano  sin informacion  sin informacion   urgencias  bloque 3                urgencias  urgencias                   alta mã©dica                 no          si               si                          j00-j99             enfermedades del sistema respiratorio          medicina interna                                 urgentologia              1      No clasificado        fast track
3     2018       mayo       4023613      2254075                    501.0       urgencias >= 24 horas  308185       contributivo  nueva eps s.a. pgp                pgp            nueva eps            nueva eps  urgencias generales sã³tano  sin informacion  sin informacion   urgencias  bloque 3                urgencias  urgencias                   alta mã©dica                 no          no  sin informacion                          i00-i99             enfermedades del sistema circulatorio          medicina interna                                 urgentologia              1      No clasificado               era
4     2018      julio       4080166      2292863                    101.0             general adultos  308185       contributivo  nueva eps s.a. pgp                pgp            nueva eps            nueva eps  urgencias generales sã³tano         bloque 3        urgencias   urgencias  bloque 1  hospitalizacion adultos     piso 7                   alta mã©dica                 no          no  sin informacion                          i00-i99             enfermedades del sistema circulatorio          medicina interna                             medicina interna              5                 era  medicina interna
5     2018    octubre       4388863      2434070                    101.0             general adultos  308185       contributivo  nueva eps s.a. pgp                pgp            nueva eps            nueva eps  urgencias generales sã³tano         bloque 3        urgencias   urgencias  bloque 1  hospitalizacion adultos     piso 4                   alta mã©dica                 no          no  sin informacion                          k00-k93                enfermedades del sistema digestivo          medicina interna                              cirugia general              6                 era  medicina interna
6     2018  noviembre       4448455      2494057                    501.0       urgencias >= 24 horas  308185       contributivo  nueva eps s.a. pgp                pgp            nueva eps            nueva eps  urgencias generales sã³tano         bloque 3        urgencias   urgencias  bloque 3                urgencias  urgencias                   alta mã©dica                 no          no  sin informacion                          j00-j99             enfermedades del sistema respiratorio           cirugia general                              cirugia general              2                 era               era
...    ...        ...           ...          ...                      ...                         ...     ...                ...                 ...                ...                  ...                  ...                          ...              ...              ...         ...       ...          

## Usuarios

In [49]:
#ANDREA
#dfusuarios=pd.read_csv('/content/drive/MyDrive/caso salud analitica /RETO_df_usuarios.csv')# ,encoding='unicode_escape', on_bad_lines='skip')
#print(dfusuarios.shape)

In [50]:
dfusuarios=pd.read_csv('/content/drive/MyDrive/Analitica3/EntregaSalud/Entregable/RETO_df_usuariosutf.csv')# ,encoding='unicode_escape', on_bad_lines='skip')
print(dfusuarios.shape)

(183911, 16)


<ipython-input-50-2fd3b6420ed8>:1: DtypeWarning: Columns (4,6,7,9,10,11,12) have mixed types. Specify dtype option on import or set low_memory=False.
  dfusuarios=pd.read_csv('/content/drive/MyDrive/Analitica3/EntregaSalud/Entregable/RETO_df_usuariosutf.csv')# ,encoding='unicode_escape', on_bad_lines='skip')


In [51]:
dfusuarios.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 183911 entries, 0 to 183910
Data columns (total 16 columns):
 #   Column                         Non-Null Count   Dtype  
---  ------                         --------------   -----  
 0   MES                            183911 non-null  object 
 1   YEAR                           183911 non-null  int64  
 2   NRODOC                         183911 non-null  int64  
 3   SEXO                           183901 non-null  object 
 4   FECHA NACIMIENTO               111831 non-null  object 
 5   EDAD                           149755 non-null  float64
 6   DEPARTAMENTO                   82284 non-null   object 
 7   MUNICIPIO                      81397 non-null   object 
 8   BARRIO                         115344 non-null  object 
 9   FECHA INICIO AL PGP            125658 non-null  object 
 10  FECHA PRIMERA CLASE FUNCIONAL  87961 non-null   object 
 11  PRIMERA CLASE FUNCIONAL        89641 non-null   object 
 12  FECHA ÚLTIMA CLASE FUNCIONAL 

In [52]:
for columna in dfusuarios.columns[:]:
  print('\n {}'.format(columna))
  print(dfusuarios[columna].unique())


 MES
['ABRIL' 'MAYO' 'JUNIO' 'JULIO' 'AGOSTO' 'SEPTIEMBRE' 'OCTUBRE'
 'NOVIEMBRE' 'DICIEMBRE' 'ENERO' 'FEBRERO' 'MARZO']

 YEAR
[2017 2018 2021 2022]

 NRODOC
[306221 306222 306223 ... 314286 314287 314288]

 SEXO
['F' 'M' nan 'CARRERA 51 B 1 33' 'CL 48  95 55' 'CR 49 46 14'
 'CRR 47 N  41 32' 'CALLE 80 A 71 A 18' 'CL 94  74B  16'
 'CALLE 77E   8830' 'KR 55A 47 16  BR SANTA ANA' 'KR 92 NRO 46 97'
 'CL 55 80 54' 'CALLE 38 SUR N  29 A 54 PISO 2'
 'CR 75A   88A   27 BRR ROBLEDO KENEDY'
 'CL  40 C  SUR   29 C  31LA FLORIDA' 'CL 31 NRO 44 159']

 FECHA NACIMIENTO
['1938-09-09 00:00:00' '1974-07-03 00:00:00' '1930-08-24 00:00:00' ...
 '1965-08-01 00:00:00' '1993-06-29 00:00:00' '1956-02-14 00:00:00']

 EDAD
[ nan  68.  54.  69.  27.  25.  24.  21.  66.  49.  26.  20.  60.  82.
  63.  74.  79.  85.  81.  70.  80.  89.  64.  93.  86.  87.  43.  83.
  78.  84.  94.  71.  76.  98.  65.  51.  67.  62.  53.  61.  57.  50.
  55.  56.  88.  72.  73.  45.  92.  75.  91.  95.  77.  90.  97.  99.
  59

In [53]:
dfusuarios = dfusuarios.apply(lambda x: x.str.lower() if x.dtype == 'object' else x)

In [54]:
dfusuarios['FECHA PRIMERA CLASE FUNCIONAL'] = dfusuarios['FECHA PRIMERA CLASE FUNCIONAL'].replace('(en blanco)', np.nan)
dfusuarios['FECHA PRIMERA CLASE FUNCIONAL'] = dfusuarios['FECHA PRIMERA CLASE FUNCIONAL'].replace(' ', np.nan)
dfusuarios

MES  YEAR  NRODOC SEXO     FECHA NACIMIENTO  EDAD DEPARTAMENTO MUNICIPIO                BARRIO  FECHA INICIO AL PGP FECHA PRIMERA CLASE FUNCIONAL PRIMERA CLASE FUNCIONAL FECHA ÚLTIMA CLASE FUNCIONAL ÚLTIMA CLASE FUNCIONAL CICLO_VITAL QUINQUENIO
0       abril  2017  306221    f  1938-09-09 00:00:00   NaN          NaN       NaN                   NaN                  NaN                           NaN                     NaN                           NaN                     NaN         NaN        NaN
1       abril  2017  306222    f  1974-07-03 00:00:00   NaN          NaN       NaN                   NaN                  NaN                           NaN                     NaN                           NaN                     NaN         NaN        NaN
2       abril  2017  306223    f  1930-08-24 00:00:00   NaN          NaN       NaN                   NaN                  NaN                           NaN                     NaN                           NaN                     NaN         NaN        NaN
3       abril  2017  306224    f  1979-12-01 00:00:00   NaN          NaN       NaN                   NaN                  NaN                           NaN                     NaN                           NaN                     NaN         NaN        NaN
4       abril  2017  306225    m  1943-06-01 00:00:00   NaN          NaN       NaN                   NaN                  NaN                           NaN                     NaN                           NaN                     NaN         NaN        NaN
...       ...   ...     ...  ...                  ...   ...          ...       ...                   ...                  ...                           ...                     ...                           ...                     ...         ...        ...
183906  junio  2022  307482    f  1941-03-26 00:00:00  81.0    antioquia  medellin                   NaN  2017-04-01 00:00:00           2017-08-23 00:00:00      clase funcional 2b           2022-04-22 00:00:00      clase funcional 2a       vejez      80-84
183907  junio  2022  313801    f  1999-04-13 00:00:00  23.0    antioquia       NaN                   NaN  2021-09-02 00:00:00           2021-10-26 00:00:00       clase funcional 1           2022-01-27 00:00:00       clase funcional 1    juventud      20-24
183908  junio  2022  307738    f  1943-09-11 00:00:00  78.0    antioquia  medellin                   NaN  2017-04-01 00:00:00           2017-06-14 00:00:00      clase funcional 2b           2022-01-06 00:00:00      clase funcional 2a       vejez     75-79 
183909  junio  2022  311656    m  1940-05-26 00:00:00  82.0    antioquia  medellin                   NaN  2018-01-01 00:00:00           2018-02-21 00:00:00      clase funcional 2a           2022-03-17 00:00:00      clase funcional 2b       vejez      80-84
183910  junio  2022  309230    m  1957-05-26 00:00:00  65.0    antioquia  envigado  envigado la magnolia  2017-04-01 00:00:00           2018-08-13 00:00:00      clase funcional 2a           2022-02-09 00:00:00      clase funcional 2b       vejez     65-69 

[183911 rows x 16 columns]

In [56]:
dfusuarios = dfusuarios[dfusuarios['SEXO'].isin(['f', 'm'])]


In [57]:
dfusuarios.loc[(dfusuarios['MUNICIPIO'] == 'medellin') & dfusuarios['DEPARTAMENTO'].isna(), 'DEPARTAMENTO'] = 'antioquia'

In [58]:
dfusuarios.loc[dfusuarios['BARRIO'].notna() & dfusuarios['DEPARTAMENTO'].isna(), 'DEPARTAMENTO'] = 'antioquia'

In [59]:
dfusuarios.loc[dfusuarios['BARRIO'].str.contains('BELLO', case=False, na=False) & dfusuarios['MUNICIPIO'].isnull(), 'MUNICIPIO'] = 'BELLO'
dfusuarios.loc[dfusuarios['BARRIO'].str.contains('ITAGUI', case=False, na=False) & dfusuarios['MUNICIPIO'].isnull(), 'MUNICIPIO'] ='ITAGUI'
dfusuarios.loc[dfusuarios['BARRIO'].str.contains('ENVIGADO', case=False, na=False) & dfusuarios['MUNICIPIO'].isnull(), 'MUNICIPIO'] ='ENVIGADO'
dfusuarios.loc[dfusuarios['BARRIO'].str.contains('SABANETA', case=False, na=False) & dfusuarios['MUNICIPIO'].isnull(), 'MUNICIPIO'] ='SABANETA'
dfusuarios.loc[dfusuarios['BARRIO'].str.contains('SANTA FE DE ANTIOQUIA', case=False, na=False) & dfusuarios['MUNICIPIO'].isnull(), 'MUNICIPIO'] = 'SANTA FE DE ANTIOQUIA'
dfusuarios.loc[dfusuarios['BARRIO'].str.contains('GIRARDOTA', case=False, na=False) & dfusuarios['MUNICIPIO'].isnull(), 'MUNICIPIO'] ='GIRARDOTA'
dfusuarios.loc[dfusuarios['BARRIO'].str.contains('GUARNE', case=False, na=False) & dfusuarios['MUNICIPIO'].isnull(), 'MUNICIPIO'] ='GUARNE'
dfusuarios.loc[dfusuarios['BARRIO'].str.contains('COPACABANA', case=False, na=False) & dfusuarios['MUNICIPIO'].isnull(), 'MUNICIPIO'] ='COPACABANA'
dfusuarios.loc[dfusuarios['BARRIO'].str.contains('GIRARDOT', case=False, na=False) & dfusuarios['MUNICIPIO'].isnull(), 'MUNICIPIO'] ='GIRARDOTA'
dfusuarios.loc[dfusuarios['BARRIO'].str.contains('SANTA ELENA', case=False, na=False) & dfusuarios['MUNICIPIO'].isnull(), 'MUNICIPIO'] ='SANTA ELENA'
dfusuarios.loc[dfusuarios['BARRIO'].str.contains('LA ESTRELLA', case=False, na=False) & dfusuarios['MUNICIPIO'].isnull(), 'MUNICIPIO'] ='LA ESTRELLA'
dfusuarios.loc[dfusuarios['BARRIO'].str.contains('SAN ANTONIO DE PRADO', case=False, na=False) & dfusuarios['MUNICIPIO'].isnull(), 'MUNICIPIO'] ='SAN ANTONIO DE PRADO'
dfusuarios.loc[dfusuarios['BARRIO'].str.contains('NIQUIA', case=False, na=False) & dfusuarios['MUNICIPIO'].isnull(), 'MUNICIPIO'] ='BELLO'
dfusuarios.loc[dfusuarios['BARRIO'].str.contains('VEREDA', case=False, na=False) & dfusuarios['MUNICIPIO'].isnull(), 'MUNICIPIO'] ='VEREDA'
dfusuarios.loc[dfusuarios['BARRIO'].str.contains('LOMA EL ESCOBERO', case=False, na=False) & dfusuarios['MUNICIPIO'].isnull(), 'MUNICIPIO'] ='ENVIGADO'
dfusuarios.loc[dfusuarios['BARRIO'].str.contains('SAN JAVIER', case=False, na=False) & dfusuarios['MUNICIPIO'].isnull(), 'MUNICIPIO'] ='MEDELLIN'
dfusuarios.loc[dfusuarios['BARRIO'].str.contains('EL SALADO', case=False, na=False) & dfusuarios['MUNICIPIO'].isnull(), 'MUNICIPIO'] ='ENVIGADO'
dfusuarios.loc[dfusuarios['BARRIO'].str.contains('MADERA', case=False, na=False) & dfusuarios['MUNICIPIO'].isnull(), 'MUNICIPIO'] = 'BELLO'
dfusuarios.loc[dfusuarios['BARRIO'].str.contains('PARQUE ITAGUÃ\x8d', case=False, na=False) & dfusuarios['MUNICIPIO'].isnull(), 'MUNICIPIO'] ='ITAGUI'
dfusuarios.loc[(dfusuarios['BARRIO'].notna()) & (dfusuarios['MUNICIPIO'].isnull()), 'MUNICIPIO'] ='MEDELLIN'

In [60]:
dfusuarios.columns

Index(['MES', 'YEAR', 'NRODOC', 'SEXO', 'FECHA NACIMIENTO', 'EDAD',
       'DEPARTAMENTO', 'MUNICIPIO', 'BARRIO', 'FECHA INICIO AL PGP',
       'FECHA PRIMERA CLASE FUNCIONAL', 'PRIMERA CLASE FUNCIONAL',
       'FECHA ÚLTIMA CLASE FUNCIONAL', 'ÚLTIMA CLASE FUNCIONAL',
       'CICLO_VITAL', 'QUINQUENIO'],
      dtype='object')

In [66]:
columnas = ['FECHA INICIO AL PGP', 'FECHA PRIMERA CLASE FUNCIONAL', 'FECHA ÚLTIMA CLASE FUNCIONAL', 'FECHA NACIMIENTO']

In [67]:

dfusuarios = dfusuarios.drop(columnas, axis = 1)

In [68]:
dfusuarios.isnull().sum()

MES                            0
YEAR                           0
NRODOC                         0
SEXO                           0
EDAD                       34132
DEPARTAMENTO               37114
MUNICIPIO                  38009
BARRIO                     68543
PRIMERA CLASE FUNCIONAL    94246
ÚLTIMA CLASE FUNCIONAL    55778
CICLO_VITAL                34132
QUINQUENIO                 34132
dtype: int64

In [69]:
dfprueba = dfusuarios[dfusuarios['EDAD'].isnull()]

In [70]:
dfprueba.isnull().sum()

MES                            0
YEAR                           0
NRODOC                         0
SEXO                           0
EDAD                       34132
DEPARTAMENTO               29526
MUNICIPIO                  29526
BARRIO                     29526
PRIMERA CLASE FUNCIONAL    34132
ÚLTIMA CLASE FUNCIONAL    31248
CICLO_VITAL                34132
QUINQUENIO                 34132
dtype: int64

In [71]:
dfusuarios = dfusuarios.dropna(subset=['EDAD'])

In [72]:
dfusuarios1 = dfusuarios.dropna(subset=['PRIMERA CLASE FUNCIONAL'])

In [73]:
dfusuarios1.isnull().sum()

MES                            0
YEAR                           0
NRODOC                         0
SEXO                           0
EDAD                           0
DEPARTAMENTO                1491
MUNICIPIO                   2221
BARRIO                     32328
PRIMERA CLASE FUNCIONAL        0
ÚLTIMA CLASE FUNCIONAL        0
CICLO_VITAL                    0
QUINQUENIO                     0
dtype: int64

In [74]:
# Porcentaje de nulos que presenta nuetra base de datos
round(dfusuarios.isnull().sum().sum()/dfusuarios.size, 4)*100

7.779999999999999

In [75]:
dfusuarios = dfusuarios.fillna('sin informacion')

In [76]:
dfusuarios = dfusuarios.drop(columns=['DEPARTAMENTO']) #lo borramos porque solo hay Antioquia y sin info y no aporta al modelo o a los datos

In [77]:
dfusuarios = dfusuarios.apply(lambda x: x.str.lower() if x.dtype == 'object' else x)
dfusuarios['EDAD'] = dfusuarios['EDAD'].apply(lambda x: min(x, 95))

In [78]:
dfusuarios = dfusuarios.drop(columns=['BARRIO'])

In [79]:
dfusuarios['PRIMERA CLASE FUNCIONAL'] = dfusuarios['PRIMERA CLASE FUNCIONAL'].replace('sin informacion', 'sin clasificar')

In [81]:
dfusuarios['ÚLTIMA CLASE FUNCIONAL'] = dfusuarios['ÚLTIMA CLASE FUNCIONAL'].replace('sin informacion', 'sin clasificar')

In [82]:
#llevar tabla a sql
dfusuarios.to_sql('usuarios', conn, index=False, if_exists='replace')

149755

## Cronicos

In [ ]:
#ANDREA
#dfcronicos=pd.read_csv('/content/drive/MyDrive/caso salud analitica /RETO_df_cronicos.csv', sep = ',' ,encoding='unicode_escape', on_bad_lines='skip')
#print(dfcronicos.shape)
#print(dfcronicos.info())
#dfcronicos

In [83]:
dfcronicos=pd.read_csv('/content/drive/MyDrive/Analitica3/EntregaSalud/Entregable/RETO_df_cronicoscsvutf.csv', sep = ';')# ,encoding='unicode_escape', on_bad_lines='skip')
print(dfcronicos.shape)
print(dfcronicos.info())
dfcronicos

<ipython-input-83-109787181774>:1: DtypeWarning: Columns (24,25,34,36,39,40,50,52,55,56,58,62,64,65,66,75,107,108,111,122,123,124,125,126,127,128,129,130,131,132,133,134,135,136,137,138,139,140,141,142,143,144,145,146,147,148,149,150,151,152,153,154,155,156,157,158,159,160,161,162,163,164,165,166,167,168,169,170,171,172,173,174,175,176,177,178,179,180,181,182,183,184,185,186,187,188,189,190,191,192,193,194,195,196,197,198,199,200,201,202,203,204,205,206,207,208,209,210,211,212,213,214,215,216,217,218,219,220,221,222,223,224,225,226,227,228,229,230,231,232,233,234,235,236,237,238,239,240,241,242,243,244,245,246,247,248,249,250,251,252,253,254,255,256,257,258,259,260,261,262,263,264,265,266,267,268,269,270,271,272,273,274,275,276,277,278,279,280,281,282,283,284,285,286,287,288,289) have mixed types. Specify dtype option on import or set low_memory=False.
  dfcronicos=pd.read_csv('/content/drive/MyDrive/Analitica3/EntregaSalud/Entregable/RETO_df_cronicoscsvutf.csv', sep = ';')# ,encoding=

(38716, 290)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 38716 entries, 0 to 38715
Columns: 290 entries, YEAR to NombreDiagnostico83
dtypes: float64(36), int64(11), object(243)
memory usage: 85.7+ MB
None


YEAR      MES Fecha diligenciamiento           Hora  Atencion  Ingreso Tipo  NRODOC  Peso  Talla    IMC Clasificación IMC  Saturación de Oxígeno (%)  Perímetro Muslo  Perímetro Cintura  Pliegue Triceps  Pliegue Abdomen  Pliegue Muslo  Sumatoria Pliegues  Presión Arterial Sistólica  Presión Arterial Diastólica  Frecuencia Cardíaca en reposo  Auto-calificacion Nivel de Ejercicio  Constantes METS -Índice Metabólico VO2 - Máxima Cantidad de Oxígeno  Índice de Fragilidad Groningen Calificación (Índice de Fragilidad)  Tiempo en Segundos (Apoyo Monopodal) Calificación (Apoyo Monopodal)  Tiempo en Segundos (Recorrer 5 metros)  Velocidad (m/s) Calificación Velocidad                  Test Findrisc Índice Tobillo/Brazo Observaciones Presión arterial registro medico Diabetes Mellitus                            Tipo diabetes mellitus Es insulinorequiriente Tiempo con el diagnóstico  Glicemia   Fecha glicemia  Hemoglobina Glicada Fecha hemoglobina glicosilada Control Diabetes Tiene riesgo de tener Diabetes Mellitus Tiene HTA    Control HTA Tiene riesgo de tener HTA Tiempo con el diagnóstico1 Tiene EPOC Espirometria  VEF1/CVF  VEF1/VFC Posbroncodilatador Gravedad Diagnóstico EPOC  Disnea MMRC Clasificación  CAT  Número de exacerbaciones último año (Que hayan necesitado hospitalizado)  Clasificación GOLD Clasificación1  Clasificación BODEX Oxígeno dependiente Tiene gases arteriales Resultado EPOC (Clasificación BODEX) Enfermedad Coronaria (En el último año) Insuficiencia Cardíaca Valvulopatía Arritmia o paciente con dispositivo Sufre de alguna enfermedad cardiovascular                             ¿Cuál? Tabaquismo Cuantos cigarrillos día  Años de Consumo  Indice paquete/año  Lipoproteina       Fecha LDL    HDL        Fecha HDL  Colesterol total Fecha colesterol total  Trigliceridos Fecha trigliceridos Clasificación de Framinghan  Creatinina 1 consulta Fecha creatinina1  Tasa de Filtración Glomerular TFG Estadio de la Enfermedad Renal  Microalbuminuria Fecha microalbuminuria  Hormona Estimulante de la Tiroides (TSH)  Otras Morbilidades     Clase Funcional  Creatinina 2 consulta Fecha creatinina2  Tasa de Filtración Glomerular TFG2  Meses de diferencia entre TFG  Cambio de TFG Clasificación Cambio de TFG Última mamografía Última citología Última cita odontológica Última cita con Optometría / Oftallmología Último PSA    Basciloscopia       Fecha basciloscopia Última vacuna de influenza Fecha Vacuna Neumococo Fecha vacuna neumococo veintitrés valentes Úlcera de pie diabético Remisión                             Diagnóstico Principal                      Análisis y conducta a seguir Tiene próximo control Fecha Próximo Control Tipo control Requiere cita de morbilidad Fecha cita morbilidad Ambito según el médico Diagnostico1 NombreDiagnostico1 Diagnostico2 NombreDiagnostico2 Diagnostico3 NombreDiagnostico3 Diagnostico4 NombreDiagnostico4 Diagnostico5 NombreDiagnostico5 Diagnostico6 NombreDiagnostico6 Diagnostico7 NombreDiagnostico7 Diagnostico8 NombreDiagnostico8 Diagnostico9 NombreDiagnostico9 Diagnostico10 NombreDiagnostico10 Diagnostico11 NombreDiagnostico11 Diagnostico12 NombreDiagnostico12 Diagnostico13 NombreDiagnostico13 Diagnostico14 NombreDiagnostico14 Diagnostico15 NombreDiagnostico15 Diagnostico16 NombreDiagnostico16 Diagnostico17 NombreDiagnostico17 Diagnostico18 NombreDiagnostico18 Diagnostico19 NombreDiagnostico19 Diagnostico20 NombreDiagnostico20 Diagnostico21 NombreDiagnostico21 Diagnostico22 NombreDiagnostico22 Diagnostico23 NombreDiagnostico23 Diagnostico24 NombreDiagnostico24 Diagnostico25 NombreDiagnostico25 Diagnostico26 NombreDiagnostico26 Diagnostico26.1 NombreDiagnostico26.1 Diagnostico27 NombreDiagnostico27 Diagnostico28 NombreDiagnostico28 Diagnostico29 NombreDiagnostico29 Diagnostico30 NombreDiagnostico30 Diagnostico31 NombreDiagnostico31 Diagnostico32 NombreDiagnostico32 Diagnostico33 NombreDiagnostico33 Diagnostico34 NombreDiagnostico34 Diagnostico35 Nomb

In [84]:
dfcronicos.rename(columns={ 'Atención': 'atencion', 'Fecha Próximo Control': 'fecha proximo control','Índice de Fragilidad Groningen': 'Indice de Fragilidad Groningen','Índice Tobillo/Brazo' : 'Indice Tobillo/Brazo', 'EPOC (Clasificación BODEX)': 'EPOC (Clasificacion BODEX)', 'Enfermedad Coronaria (En el último año)': 'Enfermedad Coronaria (En el ultimo año)',
                           'Insuficiencia Cardíaca' : 'Insuficiencia Cardiaca','Valvulopatía':'Valvulopatia', 'Años de Consumo':'Años de Consumo', 'Clasificación de Framinghan':'Clasificacion de Framinghan', 'Tasa de Filtración Glomerular TFG':'Tasa de Filtracion Glomerular TFG' ,'Tasa de Filtración Glomerular TFG2':'Tasa de Filtracion Glomerular TFG2',
                           'Úlcera de pie diabético':'ulcera de pie diabetico','Remisión':'Remision','Diagnóstico Principal':'Diagnostico Principal', 'Tiene próximo control':'Tiene proximo control','Ambito según el médico': 'Ambito segun el medico','Clasificación IMC':'Clasificacion IMC',
                           'Saturación de Oxígeno (%)': 'Saturacion de Oxi­geno (%)', 'Perímetro Muslo': 'Peri­metro Muslo', 'Perímetro Cintura':'Perimetro Cintura', 'Presión Arterial Sistólica': 'Presion Arterial Sistolica',
                           'Presión Arterial Diastólica':  'Presion Arterial Diastolica', 'Frecuencia Cardíaca en reposo': 'Frecuencia Cardiaca en reposo', 'METS -Índice Metabólico':'Indice Metabolico' ,
                           'VO2 - Máxima Cantidad de Oxígeno': 'VO2 - Maxima Cantidad de Oxi­geno', 'Calificación (Índice de Fragilidad)': 'CalificaciOn (Indice de Fragilidad)', 'Calificación (Apoyo Monopodal)': 'CalificaciOn (Apoyo Monopodal)', 'Calificación Velocidad': 'CalificaciOn Velocidad'
                           }, inplace=True)

In [85]:
dfcronicos = dfcronicos.apply(lambda x: x.str.lower() if x.dtype == 'object' else x)

In [86]:
dfcronicos['Fecha diligenciamiento'] = pd.to_datetime(dfcronicos['Fecha diligenciamiento']).dt.strftime('%d/%m/%Y')
dfcronicos['fecha proximo control'] = pd.to_datetime(dfcronicos['fecha proximo control']).dt.strftime('%d/%m/%Y')

<ipython-input-86-24d27e5fc80c>:1: UserWarning: Parsing dates in DD/MM/YYYY format when dayfirst=False (the default) was specified. This may lead to inconsistently parsed dates! Specify a format to ensure consistent parsing.
  dfcronicos['Fecha diligenciamiento'] = pd.to_datetime(dfcronicos['Fecha diligenciamiento']).dt.strftime('%d/%m/%Y')
<ipython-input-86-24d27e5fc80c>:2: UserWarning: Parsing dates in DD/MM/YYYY format when dayfirst=False (the default) was specified. This may lead to inconsistently parsed dates! Specify a format to ensure consistent parsing.
  dfcronicos['fecha proximo control'] = pd.to_datetime(dfcronicos['fecha proximo control']).dt.strftime('%d/%m/%Y')


In [87]:
for columna in dfcronicos.columns[:]:
  print('\n {}'.format(columna))
  print(dfcronicos[columna].unique())

Se han truncado las últimas 5000 líneas del flujo de salida.

 NombreDiagnostico2
[nan 'trastorno mixto de ansiedad y depresion'
 'gonartrosis no especificada' 'hipertension esencial (primaria)'
 'enfermedad pulmonar obstructiva cronica no especificada'
 'incontinencia urinaria no especificada'
 'obesidad debida a exceso de calorias' 'gonartrosis primaria bilateral'
 'fibrilacion y aleteo auricular'
 'enfermedad pulmonar obstructiva cronica con infeccion aguda de las vias respiratorias inferiores'
 'otra hiperlipidemia' 'enfermedad cardiaca no especificada'
 'insuficiencia cardiaca no especificada'
 'enfermedad aterosclerotica del corazon'
 'diabetes mellitus insulinodependiente con complicaciones no especificadas'
 'penfigo no especificado' 'demencia no especificada'
 'episodio depresivo moderado' 'hipotiroidismo no especificado'
 'cardiomiopatia isquemica'
 'diabetes mellitus no insulinodependiente sin mencion de complicacion'
 'fibrilaciã³n auricular persistente'
 'trastorno afectiv

In [88]:
# Generar una lista de nombres de columna desde 'NombreDiagnostico1' hasta 'NombreDiagnostico83'
diagnosticos = ['Diagnostico{}'.format(i) for i in range(1, 84)]

# La variable 'nombres_diagnosticos' ahora contiene una lista de nombres de columna individuales
print(diagnosticos)

['Diagnostico1', 'Diagnostico2', 'Diagnostico3', 'Diagnostico4', 'Diagnostico5', 'Diagnostico6', 'Diagnostico7', 'Diagnostico8', 'Diagnostico9', 'Diagnostico10', 'Diagnostico11', 'Diagnostico12', 'Diagnostico13', 'Diagnostico14', 'Diagnostico15', 'Diagnostico16', 'Diagnostico17', 'Diagnostico18', 'Diagnostico19', 'Diagnostico20', 'Diagnostico21', 'Diagnostico22', 'Diagnostico23', 'Diagnostico24', 'Diagnostico25', 'Diagnostico26', 'Diagnostico27', 'Diagnostico28', 'Diagnostico29', 'Diagnostico30', 'Diagnostico31', 'Diagnostico32', 'Diagnostico33', 'Diagnostico34', 'Diagnostico35', 'Diagnostico36', 'Diagnostico37', 'Diagnostico38', 'Diagnostico39', 'Diagnostico40', 'Diagnostico41', 'Diagnostico42', 'Diagnostico43', 'Diagnostico44', 'Diagnostico45', 'Diagnostico46', 'Diagnostico47', 'Diagnostico48', 'Diagnostico49', 'Diagnostico50', 'Diagnostico51', 'Diagnostico52', 'Diagnostico53', 'Diagnostico54', 'Diagnostico55', 'Diagnostico56', 'Diagnostico57', 'Diagnostico58', 'Diagnostico59', 'Diag

In [89]:
# Generar una lista de nombres de columna desde 'NombreDiagnostico1' hasta 'NombreDiagnostico83'
nombres_diagnosticos = ['NombreDiagnostico{}'.format(i) for i in range(1, 84)]

# La variable 'nombres_diagnosticos' ahora contiene una lista de nombres de columna individuales
print(nombres_diagnosticos)

['NombreDiagnostico1', 'NombreDiagnostico2', 'NombreDiagnostico3', 'NombreDiagnostico4', 'NombreDiagnostico5', 'NombreDiagnostico6', 'NombreDiagnostico7', 'NombreDiagnostico8', 'NombreDiagnostico9', 'NombreDiagnostico10', 'NombreDiagnostico11', 'NombreDiagnostico12', 'NombreDiagnostico13', 'NombreDiagnostico14', 'NombreDiagnostico15', 'NombreDiagnostico16', 'NombreDiagnostico17', 'NombreDiagnostico18', 'NombreDiagnostico19', 'NombreDiagnostico20', 'NombreDiagnostico21', 'NombreDiagnostico22', 'NombreDiagnostico23', 'NombreDiagnostico24', 'NombreDiagnostico25', 'NombreDiagnostico26', 'NombreDiagnostico27', 'NombreDiagnostico28', 'NombreDiagnostico29', 'NombreDiagnostico30', 'NombreDiagnostico31', 'NombreDiagnostico32', 'NombreDiagnostico33', 'NombreDiagnostico34', 'NombreDiagnostico35', 'NombreDiagnostico36', 'NombreDiagnostico37', 'NombreDiagnostico38', 'NombreDiagnostico39', 'NombreDiagnostico40', 'NombreDiagnostico41', 'NombreDiagnostico42', 'NombreDiagnostico43', 'NombreDiagnostico4

In [90]:
dfcronicos['count_diagnosticos'] = dfcronicos[nombres_diagnosticos].count(axis=1)

In [91]:
dfcronicos['count_diagnosticos'].unique()

array([ 0,  1,  4,  2,  3,  5,  6, 12,  8,  9,  7, 14, 10, 11, 13, 16, 18,
       22, 17, 35, 15, 47, 24, 44, 51, 20, 29, 32, 37, 55, 21, 62, 41, 53,
       83, 26, 27, 42, 19, 25, 39, 40, 30, 78, 50, 46, 72, 23, 45, 48, 54,
       81, 28, 60, 43, 64, 36, 31, 56, 38, 33, 58, 49, 66, 80, 77])

In [92]:
dfcronicos = dfcronicos.drop(columns=nombres_diagnosticos)

In [93]:
dfcronicos = dfcronicos.drop(columns=diagnosticos)

In [94]:
dfcronicos = dfcronicos.drop(columns=['Diagnostico26.1' ,'Fecha diligenciamiento', 'Hora','Observaciones', 'Es insulinorequiriente' , 'Clasificación',  '¿Cuál?', 'Análisis y conducta a seguir', ])

In [95]:
dfcronicos['Tipo'] = dfcronicos['Tipo'].str.rstrip()

In [96]:
dfcronicos.drop(columns=['Otras Morbilidades','Basciloscopia'], inplace=True)

In [97]:
dfcronicos = dfcronicos.drop(columns='fecha proximo control')

In [98]:
dfcronicos['Peso'] = dfcronicos['Peso'].round(1)

In [99]:
dfcronicos['Peso'].astype(int)

0        69
1        62
2        89
3        88
4        58
         ..
38711    65
38712    60
38713    48
38714    60
38715    75
Name: Peso, Length: 38716, dtype: int64

In [100]:
dfcronicos['Saturacion de Oxi­geno (%)'].isnull().sum()

140

In [101]:
median_value = dfcronicos['Saturacion de Oxi­geno (%)'].median()

# Llena los valores nulos con la mediana
dfcronicos['Saturacion de Oxi­geno (%)'].fillna(median_value, inplace=True)

In [102]:
dfcronicos['Indice Metabolico'].unique()

array(['63.376', '41.023', '7.015', ..., '37.026', '79.785', '75.581'],
      dtype=object)

In [103]:
umbral = 50

# Calcula el porcentaje de nulos por columna
porcentaje_nulos_por_columna = (dfcronicos.isnull().sum() / len(dfcronicos)) * 100

# Filtra las columnas con más del 70% de nulos
columnas_mas_50_nulos = porcentaje_nulos_por_columna[porcentaje_nulos_por_columna > umbral]

# Muestra las columnas con más del 70% de nulos
print("Columnas con más del 70% de nulos:")
print(columnas_mas_50_nulos)

Columnas con más del 70% de nulos:
Indice Metabolico                                                              84.130592
VO2 - Maxima Cantidad de Oxi­geno                                              68.261184
Presión arterial registro medico                                              59.161587
Tiempo con el diagnóstico                                                     65.613700
Tiene riesgo de tener Diabetes Mellitus                                        72.032235
Tiempo con el diagnóstico1                                                    64.562455
Espirometria                                                                   99.919930
VEF1/CVF                                                                       99.046906
VEF1/VFC Posbroncodilatador                                                    99.046906
Gravedad                                                                       99.943176
Diagnóstico EPOC                                                          

In [104]:
columnas_a_eliminar = columnas_mas_50_nulos.index

# Elimina las columnas del DataFrame
dfcronicos = dfcronicos.drop(columnas_a_eliminar, axis=1)

In [105]:
# Calcula la suma de valores nulos por columna
nulos_por_columna = dfcronicos.isnull().sum()

# Filtra las columnas con valores nulos (suma mayor que cero)
columnas_con_nulos = nulos_por_columna[nulos_por_columna > 0]

# Muestra las columnas con valores nulos
print(columnas_con_nulos)

Indice de Fragilidad Groningen                  47
Test Findrisc                                12760
Indice Tobillo/Brazo                         18639
Diabetes Mellitus                              871
Tipo diabetes mellitus                       13695
Glicemia                                       871
Fecha glicemia                                2454
Hemoglobina Glicada                            871
Fecha hemoglobina glicosilada                 3631
Control Diabetes                               871
Tiene HTA                                      871
Control HTA                                  10721
Tiene riesgo de tener HTA                    10721
Tiene EPOC                                     871
EPOC (Clasificacion BODEX)                   18002
Enfermedad Coronaria (En el ultimo año)        871
Insuficiencia Cardiaca                         871
Valvulopatia                                   871
Arritmia o paciente con dispositivo            871
Sufre de alguna enfermedad card

In [106]:
# Calcula la moda de las columnas
moda_fragilidad = dfcronicos['Indice de Fragilidad Groningen'].mode()[0]
moda_tobillo_brazo = dfcronicos['Indice Tobillo/Brazo'].mode()[0]
moda_clase_funcional = dfcronicos['Clase Funcional'].mode()[0]
moda_remision = dfcronicos['Remision'].mode()[0]
moda_diagnostico = dfcronicos['Diagnostico Principal'].mode()[0]

# Llena los valores faltantes con la moda de cada columna
dfcronicos['Indice de Fragilidad Groningen'].fillna(moda_fragilidad, inplace=True)
dfcronicos['Indice Tobillo/Brazo'].fillna(moda_tobillo_brazo, inplace=True)
dfcronicos['Clase Funcional'].fillna(moda_clase_funcional, inplace=True)
dfcronicos['Remision'].fillna(moda_remision, inplace=True)
dfcronicos['Diagnostico Principal'].fillna(moda_diagnostico, inplace=True)

In [138]:
columnas_para_llenar = ['Diabetes Mellitus','Tipo diabetes mellitus','Test Findrisc', 'Tiene HTA', 'Tiene EPOC','Arritmia o paciente con dispositivo',
 'Sufre de alguna enfermedad cardiovascular','Tabaquismo', 'Clasificacion de Framinghan',  'Tiene proximo control', 'Tipo control','Requiere cita de morbilidad',
 'Ambito segun el medico' , 'Valvulopatia']

In [139]:
dfcronicos[columnas_para_llenar] = dfcronicos[columnas_para_llenar].fillna('nd')

In [113]:
columnas_para_llenar_con_mediana = ['Glicemia', 'Hemoglobina Glicada', 'Lipoproteina', 'HDL','Colesterol total',
 'Trigliceridos', 'Creatinina 1 consulta', 'Tasa de Filtracion Glomerular TFG', 'Microalbuminuria',
 'Hormona Estimulante de la Tiroides (TSH)', 'Creatinina 2 consulta',  'Tasa de Filtracion Glomerular TFG2',
 'Meses de diferencia entre TFG','Cambio de TFG' ] #(mediana)

In [114]:
for columna in columnas_para_llenar_con_mediana:
    mediana = dfcronicos[columna].median()
    dfcronicos[columna].fillna(mediana, inplace=True)

In [135]:
columnas_para_llenar = ['Control Diabetes','Insuficiencia Cardiaca', 'Control HTA', 'Tiene riesgo de tener HTA', 'EPOC (Clasificacion BODEX)', 'Enfermedad Coronaria (En el ultimo año)']

In [136]:
dfcronicos[columnas_para_llenar] = dfcronicos[columnas_para_llenar].fillna('no aplica')

In [117]:
dfcronicos['Estadio de la Enfermedad Renal'] =dfcronicos['Estadio de la Enfermedad Renal'].fillna('estadio 0')

In [118]:
dfcronicos.replace('sin dato', 'nd', inplace=True)

In [119]:
import numpy as np

# Llena los valores en ' Años de Consumo' con la mediana
condicion = (dfcronicos['Tabaquismo'] == 'si') | (dfcronicos['Tabaquismo'] == 'ex-fumador')
mediana_anos_consumo = dfcronicos[condicion]['Años de Consumo'].median()
dfcronicos['Años de Consumo'].fillna(mediana_anos_consumo, inplace=True)

# Llena los valores en 'Tabaquismo' con 0
dfcronicos['Tabaquismo'].fillna(0, inplace=True)

In [120]:
for columna in dfcronicos.columns[:]:
  print('\n {}'.format(columna))
  print(dfcronicos[columna].unique())


 YEAR
[2017 2018 2021 2022]

 MES
['octubre' 'noviembre' 'diciembre' 'enero' 'febrero' 'marzo' 'mayo'
 'junio' 'julio' 'agosto' 'septiembre' 'abril']

 Atencion
[3912499 3942247 3898560 ... 6102342 6117076 6121429]

 Ingreso
[2629714 2629726 2629751 ... 4314997 3630054 3434751]

 Tipo
['cc' 'ce']

 NRODOC
[311144 308418 308573 ... 314157 314080 314135]

 Peso
[6.9000e+01 6.2000e+01 8.9000e+01 8.8000e+01 5.8000e+01 4.3000e+01
 5.5000e+01 7.1000e+01 7.6000e+01 8.0000e+01 6.0000e+01 1.0400e+02
 7.8000e+01 7.4000e+01 7.0000e+01 6.1000e+01 5.4000e+01 6.3000e+01
 8.1000e+01 6.4000e+01 5.7000e+01 4.9000e+01 6.5000e+01 1.0700e+02
 7.2000e+01 7.7000e+01 9.9000e+01 6.6000e+01 4.6000e+01 6.8000e+01
 8.2000e+01 3.7000e+01 6.7000e+01 4.4000e+01 5.0000e+01 8.6000e+01
 5.3000e+01 5.6000e+01 7.5000e+01 8.7000e+01 7.3000e+01 5.1000e+01
 8.5000e+01 8.3000e+01 9.2000e+01 1.0300e+02 9.0000e+01 9.1000e+01
 1.0800e+02 7.9000e+01 8.4000e+01 4.7000e+01 9.8000e+01 5.9000e+01
 1.1200e+02 9.5000e+01 9.3000e+01 

In [121]:
dfcronicos = dfcronicos.drop(dfcronicos.filter(like='Fecha'), axis=1)

In [122]:
dfcronicos = dfcronicos.drop(dfcronicos.filter(like='Última'), axis=1)

In [123]:
dfcronicos['Tipo control'].replace('mã©dico', 'medico', inplace=True)

In [131]:
dfcronicos = dfcronicos.drop(columns='Úlcera de pie diabético')

In [140]:
# Porcentaje de nulos que presenta nuetra base de datos
round(dfcronicos.isnull().sum().sum()/dfcronicos.size, 4)*100

0.0

In [141]:
#llevar tabla a sql
dfcronicos.to_sql('cronicos', conn, index=False, if_exists='replace')

38716

## Df final

In [142]:
dfdata=dfegresos.merge(dfusuarios, on='NRODOC', how="left")

In [143]:
dfdata

YEAR_x    MES_x  NRO ATENCION  NRO INGRESO  SERVICIO HABILITADO COD         SERVICIO HABILITADO  NRODOC REGIMEN AFILIACION        EPS VALIDADA MODALIDAD CONTRATO FUENTE FINANCIACION1 FUENTE FINANCIACION2              SERVICIO ADMITE  BLOQUE ANTERIOR    PISO ANTERIOR VIA INGRESO    BLOQUE   UNIDAD ESTRATEGICA       PISO                    TIPO EGRESO TRANSFUSION SANGRE ANTIBIOTICO ALTA MEDICA DX PRINCIPAL EGRESO CAPITULO COD            DX PRINCIPAL EGRESO CAPITULO PROFESIONAL ESPECIALIDAD PROFESIONAL ESPECIALIDAD GRD  Dias_Estancia SERVICIO ANTERIOR_C SERVICIO EGRESO_C       MES_y  YEAR_y SEXO  EDAD MUNICIPIO PRIMERA CLASE FUNCIONAL ÚLTIMA CLASE FUNCIONAL CICLO_VITAL QUINQUENIO
0        2018  febrero       3912821      2159592                    501.0       urgencias >= 24 horas  308185       contributivo  nueva eps s.a. pgp                pgp            nueva eps            nueva eps  urgencias generales sã³tano  sin informacion  sin informacion   urgencias  bloque 3            urgencias  urgencias                   alta mã©dica                 no          si          si                          j00-j99  enfermedades del sistema respiratorio          medicina interna                 urgentologia              1      No clasificado        fast track  septiembre    2017    f  78.0  medellin          sin clasificar          sin clasificar       vejez     75-79 
1        2018  febrero       3912821      2159592                    501.0       urgencias >= 24 horas  308185       contributivo  nueva eps s.a. pgp                pgp            nueva eps            nueva eps  urgencias generales sã³tano  sin informacion  sin informacion   urgencias  bloque 3            urgencias  urgencias                   alta mã©dica                 no          si          si                          j00-j99  enfermedades del sistema respiratorio          medicina interna                 urgentologia              1      No clasificado        fast track     octubre    2017    f  79.0  medellin          sin clasificar      clase funcional 2b       vejez     75-79 
2        2018  febrero       3912821      2159592                    501.0       urgencias >= 24 horas  308185       contributivo  nueva eps s.a. pgp                pgp            nueva eps            nueva eps  urgencias generales sã³tano  sin informacion  sin informacion   urgencias  bloque 3            urgencias  urgencias                   alta mã©dica                 no          si          si                          j00-j99  enfermedades del sistema respiratorio          medicina interna                 urgentologia              1      No clasificado        fast track   diciembre    2017    f  79.0  medellin          sin clasificar      clase funcional 2b       vejez     75-79 
3        2018  febrero       3912821      2159592                    501.0       urgencias >= 24 horas  308185       contributivo  nueva eps s.a. pgp                pgp            nueva eps            nueva eps  urgencias generales sã³tano  sin informacion  sin informacion   urgencias  bloque 3            urgencias  urgencias                   alta mã©dica                 no          si          si                          j00-j99  enfermedades del sistema respiratorio          medicina interna                 urgentologia              1      No clasificado        fast track       enero    2018    f  79.0  medellin          sin clasificar      clase funcional 2b       vejez     75-79 
4        2018  febrero       3912821      2159592                    501.0       urgencias >= 24 horas  308185       contributivo  nueva eps s.a. pgp                pgp            nueva eps            nueva eps  urgencias generales sã³tano  sin informacion  sin informacion   urgencias  bloque 3            urgencias  urgencias                   alta mã©dica                 no          si          si                          j00-j99  enfermedades del sistema respiratorio          medicina interna                 urgentologia         

In [145]:
df1 = dfdata.merge(dfcronicos, on='NRODOC', how="inner")
df1.isnull().sum()

YEAR_x                         0
MES_x                          0
NRO ATENCION                   0
NRO INGRESO                    0
SERVICIO HABILITADO COD        0
                              ..
Tiene proximo control          0
Tipo control                   0
Requiere cita de morbilidad    0
Ambito segun el medico         0
count_diagnosticos             0
Length: 109, dtype: int64

In [146]:
df1

YEAR_x    MES_x  NRO ATENCION  NRO INGRESO  SERVICIO HABILITADO COD         SERVICIO HABILITADO  NRODOC REGIMEN AFILIACION        EPS VALIDADA MODALIDAD CONTRATO FUENTE FINANCIACION1 FUENTE FINANCIACION2              SERVICIO ADMITE  BLOQUE ANTERIOR    PISO ANTERIOR VIA INGRESO    BLOQUE   UNIDAD ESTRATEGICA       PISO                    TIPO EGRESO TRANSFUSION SANGRE ANTIBIOTICO ALTA MEDICA DX PRINCIPAL EGRESO CAPITULO COD            DX PRINCIPAL EGRESO CAPITULO PROFESIONAL ESPECIALIDAD PROFESIONAL ESPECIALIDAD GRD  Dias_Estancia SERVICIO ANTERIOR_C SERVICIO EGRESO_C       MES_y  YEAR_y SEXO  EDAD MUNICIPIO PRIMERA CLASE FUNCIONAL ÚLTIMA CLASE FUNCIONAL CICLO_VITAL QUINQUENIO  igual  YEAR      MES  Atencion  Ingreso Tipo  Peso  Talla    IMC Clasificacion IMC  Saturacion de Oxi­geno (%)  Peri­metro Muslo  Perimetro Cintura  Pliegue Triceps  Pliegue Abdomen  Pliegue Muslo  Sumatoria Pliegues  Presion Arterial Sistolica  Presion Arterial Diastolica  Frecuencia Cardiaca en reposo  Auto-calificacion Nivel de Ejercicio  Constantes  Indice de Fragilidad Groningen CalificaciOn (Indice de Fragilidad)  Tiempo en Segundos (Apoyo Monopodal) CalificaciOn (Apoyo Monopodal)  Tiempo en Segundos (Recorrer 5 metros)  Velocidad (m/s) CalificaciOn Velocidad                  Test Findrisc Indice Tobillo/Brazo Diabetes Mellitus                        Tipo diabetes mellitus  Glicemia  Hemoglobina Glicada   Control Diabetes Tiene HTA    Control HTA Tiene riesgo de tener HTA Tiene EPOC EPOC (Clasificacion BODEX) Enfermedad Coronaria (En el ultimo año) Insuficiencia Cardiaca Valvulopatia Arritmia o paciente con dispositivo Sufre de alguna enfermedad cardiovascular Tabaquismo  Años de Consumo  Lipoproteina   HDL  Colesterol total  Trigliceridos Clasificacion de Framinghan  Creatinina 1 consulta  Tasa de Filtracion Glomerular TFG Estadio de la Enfermedad Renal  Microalbuminuria  Hormona Estimulante de la Tiroides (TSH)     Clase Funcional  Creatinina 2 consulta  Tasa de Filtracion Glomerular TFG2  Meses de diferencia entre TFG  Cambio de TFG  Remision                              Diagnostico Principal Tiene proximo control Tipo control Requiere cita de morbilidad Ambito segun el medico  count_diagnosticos
0         2018  febrero       3912821      2159592                    501.0       urgencias >= 24 horas  308185       contributivo  nueva eps s.a. pgp                pgp            nueva eps            nueva eps  urgencias generales sã³tano  sin informacion  sin informacion   urgencias  bloque 3            urgencias  urgencias                   alta mã©dica                 no          si          si                          j00-j99  enfermedades del sistema respiratorio          medicina interna                 urgentologia              1      No clasificado        fast track  septiembre    2017    f  78.0  medellin          sin clasificar          sin clasificar       vejez     75-79   False  2017  octubre   3924121  2636986   cc  60.0  145.0  28.54         sobrepeso                        86.0                57               90.0             20.0             38.0           15.0                73.0                         133                           71                             64                                     3        1.06                             2.0                              normal                                    20                      aceptable                                       5             1.00              aceptable  alta probabilidad de diabetes   0.91 - 1.30 normal                no                                            nd      74.0                 0.00          no aplica        si     controlada                 no aplica         si                   moderada                               no aplica              no aplica           no                                  no                                        si         no             30.0          79.0  63.0             157.0           75.0                 bajo ri

In [ ]:
#llevar tabla a sql
df1.to_sql('final', conn, index=False, if_exists='replace')

In [148]:
#ver las tablas que hay en la base de datos
cur.execute("select name from sqlite_master where type='table' ")
cur.fetchall()

[('egresos',), ('usuarios',), ('cronicos',), ('final',)]

Graficos

In [ ]:
df1

In [ ]:
# Obtiene estadísticas descriptivas de las columnas numéricas
df1.describe()

In [ ]:
# Cuenta el número de valores únicos en cada columna
df1.nunique()

In [ ]:
df1.columns

In [ ]:
# Matriz de correlación
corr_matrix = df1.corr()
corr_matrix


In [ ]:
import seaborn as sns
import matplotlib.pyplot as plt
# Mapa de calor de la matriz de correlación
plt.figure(figsize=(10,10))
sns.heatmap(corr_matrix, annot=True)
plt.title('Matriz de correlación')
plt.show()