<a href="https://colab.research.google.com/github/angelaguzmanar/Salud/blob/main/Preprocesamiento_Salud.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [66]:
import pandas as pd ### para manejo de datos
import sys
import numpy as np
import sqlite3 as sql

In [2]:
  #conectamos con Google Drive
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


## Egresos

In [3]:
dfegresos=pd.read_csv('/content/drive/MyDrive/Analitica3/EntregaSalud/Entregable/RETO_df_egresoscsv.csv', sep = ';' ,encoding='unicode_escape', on_bad_lines='skip')
print(dfegresos.shape)
dfegresos.info()

(6376, 66)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6376 entries, 0 to 6375
Data columns (total 66 columns):
 #   Column                             Non-Null Count  Dtype 
---  ------                             --------------  ----- 
 0   YEAR                               6376 non-null   int64 
 1   MES                                6376 non-null   object
 2   NRO ATENCION                       6376 non-null   int64 
 3   NRO INGRESO                        6376 non-null   int64 
 4   SERVICIO HABILITADO COD            6376 non-null   int64 
 5   SERVICIO HABILITADO                6376 non-null   object
 6   TIPO IDENTIFICACION                6376 non-null   object
 7   NRODOC                             6376 non-null   int64 
 8   FECHA NACIMIENTO                   6376 non-null   object
 9   REGIMEN AFILIACION                 6376 non-null   object
 10  EPS VALIDADA                       4103 non-null   object
 11  MODALIDAD CONTRATO                 6376 non-null   object


In [4]:
# Calcula la suma de valores nulos por columna
nulos_por_columna = dfegresos.isnull().sum()

# Filtra las columnas con valores nulos (suma mayor que cero)
columnas_con_nulos = nulos_por_columna[nulos_por_columna > 0]

# Muestra las columnas con valores nulos
print(columnas_con_nulos)

EPS VALIDADA                         2273
FECHA INGRESO CLINICA                2271
FECHA INGRESO SERVICIO               2272
FECHA POSIBLE ALTA                   6223
FECHA RECAUDO                        4777
FECHA CAMILLERO                      4540
FECHA ENFERMERIA                     4923
FECHA FACTURACION AUDIFARMA          4296
FECHA FARMACIA                       4315
FECHA ASEO                           4395
DX RELACIONADO1 COD                    19
DX RELACIONADO2 COD                    67
DX RELACIONADO3 COD                   181
PERTINENCIA DIAGNOSTICA              5192
DX PRINCIPAL EGRESO CATEGORIA COD      72
DX PRINCIPAL EGRESO CAPITULO COD       72
CAUSA BASICA MUERTE COD              5810
CAUSA BASICA CATEGORIA COD           5812
CAUSA BASICA CAPITULO COD            5812
dtype: int64


In [5]:
dfegresos = dfegresos.apply(lambda x: x.str.lower() if x.dtype == 'object' else x)

In [6]:
dfegresos.drop('FECHA NACIMIENTO', axis=1, inplace=True)

In [7]:
dfegresos['FECHA INGRESO CLINICA'].unique()

array([nan, '21:03.3', '07:11.0', ..., '06:14.9', '03:15.8', '27:30.3'],
      dtype=object)

In [8]:
pd.set_option('display.max_columns', None)
pd.set_option('display.expand_frame_repr', False)
dfegresos[dfegresos['EPS VALIDADA'].isnull()]
dfegresos

YEAR        MES  NRO ATENCION  NRO INGRESO  SERVICIO HABILITADO COD         SERVICIO HABILITADO TIPO IDENTIFICACION  NRODOC REGIMEN AFILIACION        EPS VALIDADA MODALIDAD CONTRATO FUENTE FINANCIACION1 FUENTE FINANCIACION2              SERVICIO ADMITE  BLOQUE ANTERIOR    PISO ANTERIOR           SERVICIO ANTERIOR NRO CAMA ANTERIOR                       VIA INGRESO           BLOQUE       UNIDAD ESTRATEGICA             PISO         NRO CAMA                SERVICIO EGRESO                    TIPO EGRESO FECHA INGRESO CLINICA FECHA INGRESO SERVICIO FECHA POSIBLE ALTA FECHA ALTA MEDICA FECHA RECAUDO FECHA CAMILLERO FECHA ENFERMERIA FECHA FACTURACION AUDIFARMA FECHA FARMACIA FECHA SALIDA FECHA ASEO DEMORA ASIGNACION CAMA DEMORA APLICACION MEDICAMENTO  DEMORA SALIDA CLINICA (DIAS) TRANSFUSION SANGRE ANTIBIOTICO      ALTA MEDICA     POSIBLE ALTA DXPRINCIPAL EGRESO COD                                 DXPRINCIPAL EGRESO DX RELACIONADO1 COD                                    DX RELACIONADO1 DX RELACIONADO2 COD                                    DX RELACIONADO2 DX RELACIONADO3 COD                                    DX RELACIONADO3 TIPO DIAGNOSTICO PRINCIPAL PERTINENCIA DIAGNOSTICA DX PRINCIPAL EGRESO CATEGORIA COD                      DX PRINCIPAL EGRESO CATEGORIA DX PRINCIPAL EGRESO CAPITULO COD                       DX PRINCIPAL EGRESO CAPITULO CAUSA BASICA MUERTE COD               CAUSA BASICA MUERTE CAUSA BASICA CATEGORIA COD            CAUSA BASICA CATEGORIA CAUSA BASICA CAPITULO COD             CAUSA BASICA CAPITULO          PROFESIONAL ESPECIALIDAD                 PROFESIONAL ESPECIALIDAD GRD
0     2017       mayo       3433964      1899917                       -1             sin informacion                  cc  308185   sin informaciã³n                 NaN   sin informaciã³n     sin informaciã³n     sin informaciã³n  urgencias generales sã³tano  sin informacion  sin informacion             sin informacion   sin informacion  sin informacion en base de datos  sin informacion  hospitalizacion adultos  sin informacion  sin informacion                sin informacion               sin informaciã³n                   NaN                    NaN                NaN           03:57.6           NaN             NaN              NaN                         NaN            NaN      55:02.0        NaN                   0:00                          0:00                             0                 no          no  sin informacion  sin informacion                   j441  enfermedad pulmonar obstructiva cronica con ex...                j984                        otros trastornos del pulmon                j432                             enfisema centrolobular                j981                                  colapso pulmonar             sin informacion                     NaN                               j44  otras enfermedades pulmonares obstructivas cro...                          j00-j99             enfermedades del sistema respiratorio                      NaN  sin informacion en base de datos                        NaN  sin informacion en base de datos                       NaN  sin informacion en base de datos  sin informacion en base de datos                             medicina interna
1     2017  diciembre       3720631      2018136                       -1             sin informacion                  cc  308185   sin informaciã³n                 NaN   sin informaciã³n     sin informaciã³n     sin informaciã³n  urgencias generales sã³tano  sin informacion  sin informacion             sin informacion   sin informacion  sin informacion en base de datos  sin informacion  hospitalizacion adultos  sin informacion  sin informacion                sin informacion               sin informaciã³n                   NaN                    NaN                NaN           35:27.1           NaN             NaN              NaN                         NaN            NaN      06:49.0        NaN                   0:00                          0:00       

In [9]:
dfegresos1 = dfegresos.copy()

In [10]:
dfegresos1.columns

Index(['YEAR', 'MES', 'NRO ATENCION', 'NRO INGRESO', 'SERVICIO HABILITADO COD',
       'SERVICIO HABILITADO', 'TIPO IDENTIFICACION', 'NRODOC',
       'REGIMEN AFILIACION', 'EPS VALIDADA', 'MODALIDAD CONTRATO',
       'FUENTE FINANCIACION1', 'FUENTE FINANCIACION2', 'SERVICIO ADMITE',
       'BLOQUE ANTERIOR', 'PISO ANTERIOR', 'SERVICIO ANTERIOR',
       'NRO CAMA ANTERIOR', 'VIA INGRESO', 'BLOQUE', 'UNIDAD ESTRATEGICA',
       'PISO', 'NRO CAMA', 'SERVICIO EGRESO', 'TIPO EGRESO',
       'FECHA INGRESO CLINICA', 'FECHA INGRESO SERVICIO', 'FECHA POSIBLE ALTA',
       'FECHA ALTA MEDICA', 'FECHA RECAUDO', 'FECHA CAMILLERO',
       'FECHA ENFERMERIA', 'FECHA FACTURACION AUDIFARMA', 'FECHA FARMACIA',
       'FECHA SALIDA', 'FECHA ASEO', 'DEMORA ASIGNACION CAMA',
       'DEMORA APLICACION MEDICAMENTO', 'DEMORA SALIDA CLINICA (DIAS)',
       'TRANSFUSION SANGRE', 'ANTIBIOTICO', 'ALTA MEDICA', 'POSIBLE ALTA',
       'DXPRINCIPAL EGRESO COD', 'DXPRINCIPAL EGRESO', 'DX RELACIONADO1 COD',
       '

In [11]:
columnas = ['FECHA INGRESO CLINICA', 'FECHA INGRESO SERVICIO', 'FECHA POSIBLE ALTA',
       'FECHA ALTA MEDICA', 'FECHA RECAUDO', 'FECHA CAMILLERO',
       'FECHA ENFERMERIA', 'FECHA FACTURACION AUDIFARMA', 'FECHA FARMACIA',
       'FECHA SALIDA', 'FECHA ASEO'] #Fechas malas (?)

In [12]:
for i in columnas:
  dfegresos1.drop(i, axis=1, inplace=True)

In [13]:
for i in dfegresos1.columns[:]:
  dfegresos1[i].replace('sin informaciã³n', 'sin informacion', inplace=True)

In [14]:
for i in dfegresos1.columns[:]:
  if dfegresos1[i].dtype == object:
    dfegresos1[i].str.replace('ã³', 'o')

In [15]:
for columna in dfegresos1.columns[:]:
  print('\n {}'.format(columna))
  print(dfegresos1[columna].unique())


 YEAR
[2017 2018 2021]

 MES
['mayo' 'diciembre' 'febrero' 'julio' 'octubre' 'noviembre' 'marzo'
 'abril' 'junio' 'septiembre' 'agosto' 'enero']

 NRO ATENCION
[3433964 3720631 3912821 ... 3961138 5883105 5857866]

 NRO INGRESO
[1899917 2018136 2159592 ... 2204868 4110965 4084538]

 SERVICIO HABILITADO COD
[ -1 501 101 110 107]

 SERVICIO HABILITADO
['sin informacion' 'urgencias >= 24 horas' 'general adultos'
 'urgencias < 24 horas' 'cuidado intensivo adultos'
 'cuidado intermedio adultos']

 TIPO IDENTIFICACION
['cc' 'ce']

 NRODOC
[308185 310222 307108 ... 308759 313987 313921]

 REGIMEN AFILIACION
['sin informacion' 'contributivo' 'soat' 'subsidiado' 'particular'
 'medicina prepagada']

 EPS VALIDADA
[nan 'nueva eps s.a. pgp' 'nueva eps s.a.' 'no afiliado particular'
 'axa seguros colpatria s.a' 'allianz seguros de vida'
 'seguros generales suramericana s.a']

 MODALIDAD CONTRATO
['sin informacion' 'pgp' 'evento']

 FUENTE FINANCIACION1
['sin informacion' 'nueva eps' 'qbe seguros s

In [16]:
# Porcentaje de nulos que presenta nuetra base de datos
round(dfegresos.isnull().sum().sum()/dfegresos.size, 4)*100


15.28

## Usuarios

In [17]:
dfusuarios=pd.read_csv('/content/drive/MyDrive/Analitica3/EntregaSalud/Entregable/RETO_df_usuariosutf.csv')# ,encoding='unicode_escape', on_bad_lines='skip')
print(dfusuarios.shape)

(183911, 16)


<ipython-input-17-2fd3b6420ed8>:1: DtypeWarning: Columns (4,6,7,9,10,11,12) have mixed types. Specify dtype option on import or set low_memory=False.
  dfusuarios=pd.read_csv('/content/drive/MyDrive/Analitica3/EntregaSalud/Entregable/RETO_df_usuariosutf.csv')# ,encoding='unicode_escape', on_bad_lines='skip')


In [18]:
dfusuarios.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 183911 entries, 0 to 183910
Data columns (total 16 columns):
 #   Column                         Non-Null Count   Dtype  
---  ------                         --------------   -----  
 0   MES                            183911 non-null  object 
 1   YEAR                           183911 non-null  int64  
 2   NRODOC                         183911 non-null  int64  
 3   SEXO                           183901 non-null  object 
 4   FECHA NACIMIENTO               111831 non-null  object 
 5   EDAD                           149755 non-null  float64
 6   DEPARTAMENTO                   82284 non-null   object 
 7   MUNICIPIO                      81397 non-null   object 
 8   BARRIO                         115344 non-null  object 
 9   FECHA INICIO AL PGP            125658 non-null  object 
 10  FECHA PRIMERA CLASE FUNCIONAL  87961 non-null   object 
 11  PRIMERA CLASE FUNCIONAL        89641 non-null   object 
 12  FECHA ÚLTIMA CLASE FUNCIONAL 

In [19]:
for columna in dfusuarios.columns[:]:
  print('\n {}'.format(columna))
  print(dfusuarios[columna].unique())


 MES
['ABRIL' 'MAYO' 'JUNIO' 'JULIO' 'AGOSTO' 'SEPTIEMBRE' 'OCTUBRE'
 'NOVIEMBRE' 'DICIEMBRE' 'ENERO' 'FEBRERO' 'MARZO']

 YEAR
[2017 2018 2021 2022]

 NRODOC
[306221 306222 306223 ... 314286 314287 314288]

 SEXO
['F' 'M' nan 'CARRERA 51 B 1 33' 'CL 48  95 55' 'CR 49 46 14'
 'CRR 47 N  41 32' 'CALLE 80 A 71 A 18' 'CL 94  74B  16'
 'CALLE 77E   8830' 'KR 55A 47 16  BR SANTA ANA' 'KR 92 NRO 46 97'
 'CL 55 80 54' 'CALLE 38 SUR N  29 A 54 PISO 2'
 'CR 75A   88A   27 BRR ROBLEDO KENEDY'
 'CL  40 C  SUR   29 C  31LA FLORIDA' 'CL 31 NRO 44 159']

 FECHA NACIMIENTO
['1938-09-09 00:00:00' '1974-07-03 00:00:00' '1930-08-24 00:00:00' ...
 '1965-08-01 00:00:00' '1993-06-29 00:00:00' '1956-02-14 00:00:00']

 EDAD
[ nan  68.  54.  69.  27.  25.  24.  21.  66.  49.  26.  20.  60.  82.
  63.  74.  79.  85.  81.  70.  80.  89.  64.  93.  86.  87.  43.  83.
  78.  84.  94.  71.  76.  98.  65.  51.  67.  62.  53.  61.  57.  50.
  55.  56.  88.  72.  73.  45.  92.  75.  91.  95.  77.  90.  97.  99.
  59

In [20]:
dfusuarios = dfusuarios.apply(lambda x: x.str.lower() if x.dtype == 'object' else x)

In [21]:
dfusuarios['FECHA PRIMERA CLASE FUNCIONAL'] = dfusuarios['FECHA PRIMERA CLASE FUNCIONAL'].replace('(en blanco)', np.nan)
dfusuarios['FECHA PRIMERA CLASE FUNCIONAL'] = dfusuarios['FECHA PRIMERA CLASE FUNCIONAL'].replace(' ', np.nan)

In [22]:
dfusuarios['FECHA INICIO AL PGP'] = pd.to_datetime(dfusuarios['FECHA INICIO AL PGP']).dt.strftime('%Y-%m-%d')
dfusuarios['FECHA PRIMERA CLASE FUNCIONAL'] = pd.to_datetime(dfusuarios['FECHA PRIMERA CLASE FUNCIONAL']).dt.strftime('%Y-%m-%d')
dfusuarios['FECHA ÚLTIMA CLASE FUNCIONAL'] = pd.to_datetime(dfusuarios['FECHA ÚLTIMA CLASE FUNCIONAL']).dt.strftime('%Y-%m-%d')
dfusuarios['FECHA NACIMIENTO'] = pd.to_datetime(dfusuarios['FECHA NACIMIENTO']).dt.strftime('%Y-%m-%d')

In [23]:
#dfusuarios['ÚLTIMA CLASE FUNCIONAL'].fillna('sin clasificar', inplace=True)
#dfusuarios['PRIMERA CLASE FUNCIONAL'].fillna('sin clasificar', inplace=True)

In [24]:
dfusuarios = dfusuarios[dfusuarios['SEXO'].isin(['F', 'M'])]
dfusuarios['SEXO'].unique()

array([], dtype=object)

In [25]:
dfusuarios.loc[(dfusuarios['MUNICIPIO'] == 'MEDELLIN') & dfusuarios['DEPARTAMENTO'].isna(), 'DEPARTAMENTO'] = 'ANTIOQUIA'

In [26]:
dfusuarios.loc[dfusuarios['BARRIO'].notna() & dfusuarios['DEPARTAMENTO'].isna(), 'DEPARTAMENTO'] = 'ANTIOQUIA'

In [27]:
dfusuarios.loc[dfusuarios['BARRIO'].str.contains('BELLO', case=False, na=False) & dfusuarios['MUNICIPIO'].isnull(), 'MUNICIPIO'] = 'BELLO'
dfusuarios.loc[dfusuarios['BARRIO'].str.contains('ITAGUI', case=False, na=False) & dfusuarios['MUNICIPIO'].isnull(), 'MUNICIPIO'] ='ITAGUI'
dfusuarios.loc[dfusuarios['BARRIO'].str.contains('ENVIGADO', case=False, na=False) & dfusuarios['MUNICIPIO'].isnull(), 'MUNICIPIO'] ='ENVIGADO'
dfusuarios.loc[dfusuarios['BARRIO'].str.contains('SABANETA', case=False, na=False) & dfusuarios['MUNICIPIO'].isnull(), 'MUNICIPIO'] ='SABANETA'
dfusuarios.loc[dfusuarios['BARRIO'].str.contains('SANTA FE DE ANTIOQUIA', case=False, na=False) & dfusuarios['MUNICIPIO'].isnull(), 'MUNICIPIO'] = 'SANTA FE DE ANTIOQUIA'
dfusuarios.loc[dfusuarios['BARRIO'].str.contains('GIRARDOTA', case=False, na=False) & dfusuarios['MUNICIPIO'].isnull(), 'MUNICIPIO'] ='GIRARDOTA'
dfusuarios.loc[dfusuarios['BARRIO'].str.contains('GUARNE', case=False, na=False) & dfusuarios['MUNICIPIO'].isnull(), 'MUNICIPIO'] ='GUARNE'
dfusuarios.loc[dfusuarios['BARRIO'].str.contains('COPACABANA', case=False, na=False) & dfusuarios['MUNICIPIO'].isnull(), 'MUNICIPIO'] ='COPACABANA'
dfusuarios.loc[dfusuarios['BARRIO'].str.contains('GIRARDOT', case=False, na=False) & dfusuarios['MUNICIPIO'].isnull(), 'MUNICIPIO'] ='GIRARDOTA'
dfusuarios.loc[dfusuarios['BARRIO'].str.contains('SANTA ELENA', case=False, na=False) & dfusuarios['MUNICIPIO'].isnull(), 'MUNICIPIO'] ='SANTA ELENA'
dfusuarios.loc[dfusuarios['BARRIO'].str.contains('LA ESTRELLA', case=False, na=False) & dfusuarios['MUNICIPIO'].isnull(), 'MUNICIPIO'] ='LA ESTRELLA'
dfusuarios.loc[dfusuarios['BARRIO'].str.contains('SAN ANTONIO DE PRADO', case=False, na=False) & dfusuarios['MUNICIPIO'].isnull(), 'MUNICIPIO'] ='SAN ANTONIO DE PRADO'
dfusuarios.loc[dfusuarios['BARRIO'].str.contains('NIQUIA', case=False, na=False) & dfusuarios['MUNICIPIO'].isnull(), 'MUNICIPIO'] ='BELLO'
dfusuarios.loc[dfusuarios['BARRIO'].str.contains('VEREDA', case=False, na=False) & dfusuarios['MUNICIPIO'].isnull(), 'MUNICIPIO'] ='VEREDA'
dfusuarios.loc[dfusuarios['BARRIO'].str.contains('LOMA EL ESCOBERO', case=False, na=False) & dfusuarios['MUNICIPIO'].isnull(), 'MUNICIPIO'] ='ENVIGADO'
dfusuarios.loc[dfusuarios['BARRIO'].str.contains('SAN JAVIER', case=False, na=False) & dfusuarios['MUNICIPIO'].isnull(), 'MUNICIPIO'] ='MEDELLIN'
dfusuarios.loc[dfusuarios['BARRIO'].str.contains('EL SALADO', case=False, na=False) & dfusuarios['MUNICIPIO'].isnull(), 'MUNICIPIO'] ='ENVIGADO'
dfusuarios.loc[dfusuarios['BARRIO'].str.contains('MADERA', case=False, na=False) & dfusuarios['MUNICIPIO'].isnull(), 'MUNICIPIO'] = 'BELLO'
dfusuarios.loc[dfusuarios['BARRIO'].str.contains('PARQUE ITAGUÃ\x8d', case=False, na=False) & dfusuarios['MUNICIPIO'].isnull(), 'MUNICIPIO'] ='ITAGUI'
dfusuarios.loc[(dfusuarios['BARRIO'].notna()) & (dfusuarios['MUNICIPIO'].isnull()), 'MUNICIPIO'] ='MEDELLIN'

In [28]:
dfusuarios.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 0 entries
Data columns (total 16 columns):
 #   Column                         Non-Null Count  Dtype  
---  ------                         --------------  -----  
 0   MES                            0 non-null      object 
 1   YEAR                           0 non-null      int64  
 2   NRODOC                         0 non-null      int64  
 3   SEXO                           0 non-null      object 
 4   FECHA NACIMIENTO               0 non-null      object 
 5   EDAD                           0 non-null      float64
 6   DEPARTAMENTO                   0 non-null      object 
 7   MUNICIPIO                      0 non-null      object 
 8   BARRIO                         0 non-null      object 
 9   FECHA INICIO AL PGP            0 non-null      object 
 10  FECHA PRIMERA CLASE FUNCIONAL  0 non-null      object 
 11  PRIMERA CLASE FUNCIONAL        0 non-null      object 
 12  FECHA ÚLTIMA CLASE FUNCIONAL  0 non-null      object 
 13  Ú

In [29]:
# Porcentaje de nulos que presenta nuetra base de datos
round(dfusuarios.isnull().sum().sum()/dfusuarios.size, 4)*100

<ipython-input-29-f4b94f77266a>:2: RuntimeWarning: invalid value encountered in double_scalars
  round(dfusuarios.isnull().sum().sum()/dfusuarios.size, 4)*100


nan

## Cronicos

In [30]:
dfcronicos=pd.read_csv('/content/drive/MyDrive/Analitica3/EntregaSalud/Entregable/RETO_df_cronicoscsvutf.csv', sep = ';')# ,encoding='unicode_escape', on_bad_lines='skip')
print(dfcronicos.shape)
print(dfcronicos.info())
dfcronicos

<ipython-input-30-109787181774>:1: DtypeWarning: Columns (24,25,34,36,39,40,50,52,55,56,58,62,64,65,66,75,107,108,111,122,123,124,125,126,127,128,129,130,131,132,133,134,135,136,137,138,139,140,141,142,143,144,145,146,147,148,149,150,151,152,153,154,155,156,157,158,159,160,161,162,163,164,165,166,167,168,169,170,171,172,173,174,175,176,177,178,179,180,181,182,183,184,185,186,187,188,189,190,191,192,193,194,195,196,197,198,199,200,201,202,203,204,205,206,207,208,209,210,211,212,213,214,215,216,217,218,219,220,221,222,223,224,225,226,227,228,229,230,231,232,233,234,235,236,237,238,239,240,241,242,243,244,245,246,247,248,249,250,251,252,253,254,255,256,257,258,259,260,261,262,263,264,265,266,267,268,269,270,271,272,273,274,275,276,277,278,279,280,281,282,283,284,285,286,287,288,289) have mixed types. Specify dtype option on import or set low_memory=False.
  dfcronicos=pd.read_csv('/content/drive/MyDrive/Analitica3/EntregaSalud/Entregable/RETO_df_cronicoscsvutf.csv', sep = ';')# ,encoding=

(38716, 290)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 38716 entries, 0 to 38715
Columns: 290 entries, YEAR to NombreDiagnostico83
dtypes: float64(36), int64(11), object(243)
memory usage: 85.7+ MB
None


YEAR      MES Fecha diligenciamiento           Hora  Atencion  Ingreso Tipo  NRODOC  Peso  Talla    IMC Clasificación IMC  Saturación de Oxígeno (%)  Perímetro Muslo  Perímetro Cintura  Pliegue Triceps  Pliegue Abdomen  Pliegue Muslo  Sumatoria Pliegues  Presión Arterial Sistólica  Presión Arterial Diastólica  Frecuencia Cardíaca en reposo  Auto-calificacion Nivel de Ejercicio  Constantes METS -Índice Metabólico VO2 - Máxima Cantidad de Oxígeno  Índice de Fragilidad Groningen Calificación (Índice de Fragilidad)  Tiempo en Segundos (Apoyo Monopodal) Calificación (Apoyo Monopodal)  Tiempo en Segundos (Recorrer 5 metros)  Velocidad (m/s) Calificación Velocidad                  Test Findrisc Índice Tobillo/Brazo Observaciones Presión arterial registro medico Diabetes Mellitus                            Tipo diabetes mellitus Es insulinorequiriente Tiempo con el diagnóstico  Glicemia   Fecha glicemia  Hemoglobina Glicada Fecha hemoglobina glicosilada Control Diabetes Tiene riesgo de tener Diabetes Mellitus Tiene HTA    Control HTA Tiene riesgo de tener HTA Tiempo con el diagnóstico1 Tiene EPOC Espirometria  VEF1/CVF  VEF1/VFC Posbroncodilatador Gravedad Diagnóstico EPOC  Disnea MMRC Clasificación  CAT  Número de exacerbaciones último año (Que hayan necesitado hospitalizado)  Clasificación GOLD Clasificación1  Clasificación BODEX Oxígeno dependiente Tiene gases arteriales Resultado EPOC (Clasificación BODEX) Enfermedad Coronaria (En el último año) Insuficiencia Cardíaca Valvulopatía Arritmia o paciente con dispositivo Sufre de alguna enfermedad cardiovascular                             ¿Cuál? Tabaquismo Cuantos cigarrillos día  Años de Consumo  Indice paquete/año  Lipoproteina       Fecha LDL    HDL        Fecha HDL  Colesterol total Fecha colesterol total  Trigliceridos Fecha trigliceridos Clasificación de Framinghan  Creatinina 1 consulta Fecha creatinina1  Tasa de Filtración Glomerular TFG Estadio de la Enfermedad Renal  Microalbuminuria Fecha microalbuminuria  Hormona Estimulante de la Tiroides (TSH)  Otras Morbilidades     Clase Funcional  Creatinina 2 consulta Fecha creatinina2  Tasa de Filtración Glomerular TFG2  Meses de diferencia entre TFG  Cambio de TFG Clasificación Cambio de TFG Última mamografía Última citología Última cita odontológica Última cita con Optometría / Oftallmología Último PSA    Basciloscopia       Fecha basciloscopia Última vacuna de influenza Fecha Vacuna Neumococo Fecha vacuna neumococo veintitrés valentes Úlcera de pie diabético Remisión                             Diagnóstico Principal                      Análisis y conducta a seguir Tiene próximo control Fecha Próximo Control Tipo control Requiere cita de morbilidad Fecha cita morbilidad Ambito según el médico Diagnostico1 NombreDiagnostico1 Diagnostico2 NombreDiagnostico2 Diagnostico3 NombreDiagnostico3 Diagnostico4 NombreDiagnostico4 Diagnostico5 NombreDiagnostico5 Diagnostico6 NombreDiagnostico6 Diagnostico7 NombreDiagnostico7 Diagnostico8 NombreDiagnostico8 Diagnostico9 NombreDiagnostico9 Diagnostico10 NombreDiagnostico10 Diagnostico11 NombreDiagnostico11 Diagnostico12 NombreDiagnostico12 Diagnostico13 NombreDiagnostico13 Diagnostico14 NombreDiagnostico14 Diagnostico15 NombreDiagnostico15 Diagnostico16 NombreDiagnostico16 Diagnostico17 NombreDiagnostico17 Diagnostico18 NombreDiagnostico18 Diagnostico19 NombreDiagnostico19 Diagnostico20 NombreDiagnostico20 Diagnostico21 NombreDiagnostico21 Diagnostico22 NombreDiagnostico22 Diagnostico23 NombreDiagnostico23 Diagnostico24 NombreDiagnostico24 Diagnostico25 NombreDiagnostico25 Diagnostico26 NombreDiagnostico26 Diagnostico26.1 NombreDiagnostico26.1 Diagnostico27 NombreDiagnostico27 Diagnostico28 NombreDiagnostico28 Diagnostico29 NombreDiagnostico29 Diagnostico30 NombreDiagnostico30 Diagnostico31 NombreDiagnostico31 Diagnostico32 NombreDiagnostico32 Diagnostico33 NombreDiagnostico33 Diagnostico34 NombreDiagnostico34 Diagnostico35 Nomb

In [31]:
dfcronicos = dfcronicos.apply(lambda x: x.str.lower() if x.dtype == 'object' else x)

In [32]:
dfcronicos['Fecha diligenciamiento'] = pd.to_datetime(dfcronicos['Fecha diligenciamiento']).dt.strftime('%d/%m/%Y')
dfcronicos['Fecha Próximo Control'] = pd.to_datetime(dfcronicos['Fecha Próximo Control']).dt.strftime('%d/%m/%Y')

<ipython-input-32-88e2f0db72dc>:1: UserWarning: Parsing dates in DD/MM/YYYY format when dayfirst=False (the default) was specified. This may lead to inconsistently parsed dates! Specify a format to ensure consistent parsing.
  dfcronicos['Fecha diligenciamiento'] = pd.to_datetime(dfcronicos['Fecha diligenciamiento']).dt.strftime('%d/%m/%Y')
<ipython-input-32-88e2f0db72dc>:2: UserWarning: Parsing dates in DD/MM/YYYY format when dayfirst=False (the default) was specified. This may lead to inconsistently parsed dates! Specify a format to ensure consistent parsing.
  dfcronicos['Fecha Próximo Control'] = pd.to_datetime(dfcronicos['Fecha Próximo Control']).dt.strftime('%d/%m/%Y')


In [33]:
for columna in dfcronicos.columns[:]:
  print('\n {}'.format(columna))
  print(dfcronicos[columna].unique())

Se han truncado las últimas 5000 líneas del flujo de salida.

 NombreDiagnostico2
[nan 'trastorno mixto de ansiedad y depresion'
 'gonartrosis no especificada' 'hipertension esencial (primaria)'
 'enfermedad pulmonar obstructiva cronica no especificada'
 'incontinencia urinaria no especificada'
 'obesidad debida a exceso de calorias' 'gonartrosis primaria bilateral'
 'fibrilacion y aleteo auricular'
 'enfermedad pulmonar obstructiva cronica con infeccion aguda de las vias respiratorias inferiores'
 'otra hiperlipidemia' 'enfermedad cardiaca no especificada'
 'insuficiencia cardiaca no especificada'
 'enfermedad aterosclerotica del corazon'
 'diabetes mellitus insulinodependiente con complicaciones no especificadas'
 'penfigo no especificado' 'demencia no especificada'
 'episodio depresivo moderado' 'hipotiroidismo no especificado'
 'cardiomiopatia isquemica'
 'diabetes mellitus no insulinodependiente sin mencion de complicacion'
 'fibrilaciã³n auricular persistente'
 'trastorno afectiv

In [63]:
dfc1 = dfcronicos.loc[:,['YEAR', 'MES', 'Fecha diligenciamiento', 'Hora', 'Atencion', 'Ingreso', 'Tipo', 'NRODOC', 'Peso', 'Talla', 'IMC', 'Clasificación IMC', 'Saturación de OxÃ\xadgeno (%)', 'PerÃ\xadmetro Muslo', 'PerÃ\xadmetro Cintura', 'Pliegue Triceps', 'Pliegue Abdomen', 'Pliegue Muslo', 'Sumatoria Pliegues', 'Presión Arterial Sistólica', 'Presión Arterial Diastólica', 'Frecuencia CardÃ\xadaca en reposo', 'Auto-calificacion Nivel de Ejercicio', 'Constantes', 'METS -Ã\x8dndice Metabólico', 'VO2 - Máxima Cantidad de OxÃ\xadgeno', 'Ã\x8dndice de Fragilidad Groningen', 'Calificación (Ã\x8dndice de Fragilidad)', 'Tiempo en Segundos (Apoyo Monopodal)', 'Calificación (Apoyo Monopodal)', 'Tiempo en Segundos (Recorrer 5 metros)', 'Velocidad (m/s)', 'Calificación Velocidad', 'Test Findrisc', 'Ã\x8dndice Tobillo/Brazo', 'Observaciones', 'Presión arterial registro medico', 'Diabetes Mellitus', 'Tipo diabetes mellitus', 'Es insulinorequiriente', 'Tiempo con el diagnóstico', 'Glicemia', 'Fecha glicemia', 'Hemoglobina Glicada', 'Fecha hemoglobina glicosilada', 'Control Diabetes', 'Tiene riesgo de tener Diabetes Mellitus', 'Tiene HTA', 'Control HTA', 'Tiene riesgo de tener HTA', 'Tiempo con el diagnóstico1', 'Tiene EPOC','Espirometria', 'VEF1/CVF', 'VEF1/VFC Posbroncodilatador', 'Gravedad', 'Diagnóstico EPOC', 'Disnea MMRC', 'Clasificación', 'CAT', 'Número de exacerbaciones último año (Que hayan necesitado hospitalizado)', 'Clasificación GOLD', 'Clasificación1', 'Clasificación BODEX', 'OxÃ\xadgeno dependiente', 'Tiene gases arteriales', 'Resultado', 'EPOC (Clasificación BODEX)', 'Enfermedad Coronaria (En el último año)', 'Insuficiencia CardÃ\xadaca', 'ValvulopatÃ\xada', 'Arritmia o paciente con dispositivo', 'Sufre de alguna enfermedad cardiovascular', '¿Cuál?', 'Tabaquismo', 'Cuantos cigarrillos dÃ\xada', 'Años de Consumo', 'Indice paquete/año', 'Lipoproteina', 'Fecha LDL', 'HDL', 'Fecha HDL', 'Colesterol total', 'Fecha colesterol total', 'Trigliceridos', 'Fecha trigliceridos', 'Clasificación de Framinghan', 'Creatinina 1 consulta', 'Fecha creatinina1', 'Tasa de Filtración Glomerular TFG', 'Estadio de la Enfermedad Renal', 'Microalbuminuria', 'Fecha microalbuminuria', 'Hormona Estimulante de la Tiroides (TSH)',  'Clase Funcional', 'Creatinina 2 consulta', 'Fecha creatinina2', 'Tasa de Filtración Glomerular TFG2', 'Meses de diferencia entre TFG', 'Cambio de TFG', 'Clasificación Cambio de TFG', 'Última mamografÃ\xada', 'Última citologÃ\xada', 'Última cita odontológica', 'Última cita con OptometrÃ\xada / OftallmologÃ\xada', 'Último PSA', 'Basciloscopia', 'Fecha basciloscopia', 'Última vacuna de influenza', 'Fecha Vacuna Neumococo', 'Fecha vacuna neumococo veintitrés valentes', 'Úlcera de pie diabético', 'Remisión', 'Diagnóstico Principal', 'Análisis y conducta a seguir', 'Tiene próximo control', 'Fecha Próximo Control', 'Tipo control', 'Requiere cita de morbilidad', 'Fecha cita morbilidad', 'Ambito según el médico']]

In [64]:
dfcronicos['Tipo'] = dfcronicos['Tipo'].str.rstrip()

In [36]:
dfc1['Peso'].mean()

69.78423907428454

In [65]:
for columna in dfc1.columns[:]:
  print('\n {}'.format(columna))
  print(dfc1[columna].unique()) #Otras Morbilidades toda na


 YEAR
[2017 2018 2021 2022]

 MES
['octubre' 'noviembre' 'diciembre' 'enero' 'febrero' 'marzo' 'mayo'
 'junio' 'julio' 'agosto' 'septiembre' 'abril']

 Fecha diligenciamiento
['02/10/2017' '11/10/2017' '31/10/2017' '03/10/2017' '04/10/2017'
 '05/10/2017' '06/10/2017' '09/10/2017' '25/10/2017' '13/10/2017'
 '10/10/2017' '18/10/2017' '12/10/2017' '27/10/2017' '19/10/2017'
 '17/10/2017' '23/10/2017' '30/10/2017' '20/10/2017' '24/10/2017'
 '26/10/2017' '01/11/2017' '30/11/2017' '02/11/2017' '22/11/2017'
 '03/11/2017' '07/11/2017' '29/11/2017' '08/11/2017' '24/11/2017'
 '15/11/2017' '09/11/2017' '10/11/2017' '14/11/2017' '27/11/2017'
 '16/11/2017' '17/11/2017' '20/11/2017' '21/11/2017' '23/11/2017'
 '28/11/2017' '01/12/2017' '04/12/2017' '05/12/2017' '06/12/2017'
 '29/12/2017' '07/12/2017' '11/12/2017' '12/12/2017' '13/12/2017'
 '14/12/2017' '15/12/2017' '18/12/2017' '21/12/2017' '26/12/2017'
 '19/12/2017' '20/12/2017' '27/12/2017' '22/12/2017' '28/12/2017'
 '02/01/2018' '26/01/2018' '24/0

In [39]:
dfcronicos.drop(columns=['Otras Morbilidades'], inplace=True)

In [45]:
for columna in dfcronicos.columns[:]:
  dfcronicos[columna].replace('nd', np.nan, inplace=True)

In [38]:
valores_a_reemplazar_B = ['01/06/2017 12:00:00 a. m.', '17/11/2017 12:00:00 a. m.', '29/06/2017 12:00:00 a. m.', '22/06/2018 12:00:00 a. m.', '07/12/2018 12:00:00 a. m.']

In [46]:
dfcronicos['Ambito según el médico'].fillna('sin dato', inplace=True)
dfcronicos['Basciloscopia'].replace(valores_a_reemplazar_B, np.nan, inplace=True)
dfcronicos['Tipo control'].fillna('sin dato', inplace=True)
dfcronicos['Tipo control'].replace('mã©dico', 'medico', inplace=True)

In [47]:
columnas_con_slash = dfcronicos.columns[dfcronicos.apply(lambda col: col.astype(str).str.contains('/').any())]
columnas_con_slash

Index(['Fecha diligenciamiento', 'Observaciones',
       'Presión arterial registro medico', 'Fecha glicemia',
       'Fecha hemoglobina glicosilada', '¿Cuál?', 'Fecha LDL', 'Fecha HDL',
       'Fecha colesterol total', 'Fecha trigliceridos', 'Fecha creatinina1',
       'Fecha microalbuminuria', 'Fecha creatinina2', 'Última mamografía',
       'Última citología', 'Última cita odontológica',
       'Última cita con Optometría / Oftallmología', 'Último PSA',
       'Fecha basciloscopia', 'Última vacuna de influenza',
       'Fecha Vacuna Neumococo', 'Fecha vacuna neumococo veintitrés valentes',
       'Análisis y conducta a seguir', 'Fecha Próximo Control',
       'Fecha cita morbilidad', 'NombreDiagnostico1'],
      dtype='object')

In [51]:
dfcronicos['¿Cuál?'].unique()

array([nan, 'hta, enfermedad coronaria', 'enfermedad coronaria', ...,
       'hipertension e insuficiencia cardiaca en estudio (no trae exemenes ni historia clinica',
       'estudio de arritmia cardica', 'enfermedad arterial ocusiva'],
      dtype=object)

In [55]:
fechas = ['Fecha diligenciamiento', 'Fecha glicemia',
       'Fecha hemoglobina glicosilada', 'Fecha LDL', 'Fecha HDL',
       'Fecha colesterol total', 'Fecha trigliceridos', 'Fecha creatinina1',
       'Fecha microalbuminuria', 'Fecha creatinina2', 'Última mamografía',
       'Última citología', 'Última cita odontológica',
       'Última cita con Optometría / Oftallmología', 'Último PSA',
       'Fecha basciloscopia', 'Última vacuna de influenza',
        'Fecha vacuna neumococo veintitrés valentes', 'Fecha Próximo Control',
       'Fecha cita morbilidad'] #'Fecha Vacuna Neumococo'

In [56]:
for columna in fechas:
  dfcronicos[columna] = pd.to_datetime(dfcronicos[columna]).dt.strftime('%d/%m/%Y')

<ipython-input-56-019f4992a63e>:2: UserWarning: Parsing dates in DD/MM/YYYY format when dayfirst=False (the default) was specified. This may lead to inconsistently parsed dates! Specify a format to ensure consistent parsing.
  dfcronicos[columna] = pd.to_datetime(dfcronicos[columna]).dt.strftime('%d/%m/%Y')
<ipython-input-56-019f4992a63e>:2: UserWarning: Parsing dates in DD/MM/YYYY format when dayfirst=False (the default) was specified. This may lead to inconsistently parsed dates! Specify a format to ensure consistent parsing.
  dfcronicos[columna] = pd.to_datetime(dfcronicos[columna]).dt.strftime('%d/%m/%Y')
<ipython-input-56-019f4992a63e>:2: UserWarning: Parsing dates in DD/MM/YYYY format when dayfirst=False (the default) was specified. This may lead to inconsistently parsed dates! Specify a format to ensure consistent parsing.
  dfcronicos[columna] = pd.to_datetime(dfcronicos[columna]).dt.strftime('%d/%m/%Y')
<ipython-input-56-019f4992a63e>:2: UserWarning: Parsing dates in DD/MM/YY

In [57]:
dfcronicos['Ambito según el médico'].unique()

array(['ambulatorio', 'domiciliario', 'sin dato'], dtype=object)

In [58]:
# Porcentaje de nulos que presenta nuetra base de datos
round(dfcronicos.isnull().sum().sum()/dfcronicos.size, 4)*100

72.53